/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the Forbidden type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Forbidden{}

// Forbidden Forbidden
type Forbidden struct {
	Status *ForbiddenStatus `json:"status,omitempty"`
	Data *ForbiddenData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Forbidden Forbidden

// NewForbidden instantiates a new Forbidden object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForbidden() *Forbidden {
	this := Forbidden{}
	return &this
}

// NewForbiddenWithDefaults instantiates a new Forbidden object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForbiddenWithDefaults() *Forbidden {
	this := Forbidden{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Forbidden) GetStatus() ForbiddenStatus {
	if o == nil || IsNil(o.Status) {
		var ret ForbiddenStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forbidden) GetStatusOk() (*ForbiddenStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Forbidden) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ForbiddenStatus and assigns it to the Status field.
func (o *Forbidden) SetStatus(v ForbiddenStatus) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Forbidden) GetData() ForbiddenData {
	if o == nil || IsNil(o.Data) {
		var ret ForbiddenData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forbidden) GetDataOk() (*ForbiddenData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Forbidden) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ForbiddenData and assigns it to the Data field.
func (o *Forbidden) SetData(v ForbiddenData) {
	o.Data = &v
}

func (o Forbidden) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Forbidden) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Forbidden) UnmarshalJSON(data []byte) (err error) {
	varForbidden := _Forbidden{}

	err = json.Unmarshal(data, &varForbidden)

	if err != nil {
		return err
	}

	*o = Forbidden(varForbidden)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableForbidden struct {
	value *Forbidden
	isSet bool
}

func (v NullableForbidden) Get() *Forbidden {
	return v.value
}

func (v *NullableForbidden) Set(val *Forbidden) {
	v.value = val
	v.isSet = true
}

func (v NullableForbidden) IsSet() bool {
	return v.isSet
}

func (v *NullableForbidden) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForbidden(val *Forbidden) *NullableForbidden {
	return &NullableForbidden{value: val, isSet: true}
}

func (v NullableForbidden) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForbidden) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


