/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the BadRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BadRequestData{}

// BadRequestData Validation Error
type BadRequestData struct {
	// Error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BadRequestData BadRequestData

// NewBadRequestData instantiates a new BadRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBadRequestData() *BadRequestData {
	this := BadRequestData{}
	return &this
}

// NewBadRequestDataWithDefaults instantiates a new BadRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBadRequestDataWithDefaults() *BadRequestData {
	this := BadRequestData{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *BadRequestData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BadRequestData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *BadRequestData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *BadRequestData) SetMessage(v string) {
	o.Message = &v
}

func (o BadRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BadRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BadRequestData) UnmarshalJSON(data []byte) (err error) {
	varBadRequestData := _BadRequestData{}

	err = json.Unmarshal(data, &varBadRequestData)

	if err != nil {
		return err
	}

	*o = BadRequestData(varBadRequestData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBadRequestData struct {
	value *BadRequestData
	isSet bool
}

func (v NullableBadRequestData) Get() *BadRequestData {
	return v.value
}

func (v *NullableBadRequestData) Set(val *BadRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableBadRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableBadRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBadRequestData(val *BadRequestData) *NullableBadRequestData {
	return &NullableBadRequestData{value: val, isSet: true}
}

func (v NullableBadRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBadRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


