/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the ServerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerError{}

// ServerError Internal Server Error
type ServerError struct {
	Status *ServerErrorStatus `json:"status,omitempty"`
	Data *ServerErrorData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServerError ServerError

// NewServerError instantiates a new ServerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerError() *ServerError {
	this := ServerError{}
	return &this
}

// NewServerErrorWithDefaults instantiates a new ServerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerErrorWithDefaults() *ServerError {
	this := ServerError{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServerError) GetStatus() ServerErrorStatus {
	if o == nil || IsNil(o.Status) {
		var ret ServerErrorStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetStatusOk() (*ServerErrorStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServerError) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ServerErrorStatus and assigns it to the Status field.
func (o *ServerError) SetStatus(v ServerErrorStatus) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ServerError) GetData() ServerErrorData {
	if o == nil || IsNil(o.Data) {
		var ret ServerErrorData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerError) GetDataOk() (*ServerErrorData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ServerError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ServerErrorData and assigns it to the Data field.
func (o *ServerError) SetData(v ServerErrorData) {
	o.Data = &v
}

func (o ServerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServerError) UnmarshalJSON(data []byte) (err error) {
	varServerError := _ServerError{}

	err = json.Unmarshal(data, &varServerError)

	if err != nil {
		return err
	}

	*o = ServerError(varServerError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServerError struct {
	value *ServerError
	isSet bool
}

func (v NullableServerError) Get() *ServerError {
	return v.value
}

func (v *NullableServerError) Set(val *ServerError) {
	v.value = val
	v.isSet = true
}

func (v NullableServerError) IsSet() bool {
	return v.isSet
}

func (v *NullableServerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerError(val *ServerError) *NullableServerError {
	return &NullableServerError{value: val, isSet: true}
}

func (v NullableServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


