/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the ServerErrorData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerErrorData{}

// ServerErrorData Internal Server Error
type ServerErrorData struct {
	// Error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServerErrorData ServerErrorData

// NewServerErrorData instantiates a new ServerErrorData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerErrorData() *ServerErrorData {
	this := ServerErrorData{}
	return &this
}

// NewServerErrorDataWithDefaults instantiates a new ServerErrorData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerErrorDataWithDefaults() *ServerErrorData {
	this := ServerErrorData{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerErrorData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerErrorData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerErrorData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerErrorData) SetMessage(v string) {
	o.Message = &v
}

func (o ServerErrorData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerErrorData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServerErrorData) UnmarshalJSON(data []byte) (err error) {
	varServerErrorData := _ServerErrorData{}

	err = json.Unmarshal(data, &varServerErrorData)

	if err != nil {
		return err
	}

	*o = ServerErrorData(varServerErrorData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServerErrorData struct {
	value *ServerErrorData
	isSet bool
}

func (v NullableServerErrorData) Get() *ServerErrorData {
	return v.value
}

func (v *NullableServerErrorData) Set(val *ServerErrorData) {
	v.value = val
	v.isSet = true
}

func (v NullableServerErrorData) IsSet() bool {
	return v.isSet
}

func (v *NullableServerErrorData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerErrorData(val *ServerErrorData) *NullableServerErrorData {
	return &NullableServerErrorData{value: val, isSet: true}
}

func (v NullableServerErrorData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerErrorData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


