/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the NotFoundData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotFoundData{}

// NotFoundData Resource Not Found
type NotFoundData struct {
	// Error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotFoundData NotFoundData

// NewNotFoundData instantiates a new NotFoundData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotFoundData() *NotFoundData {
	this := NotFoundData{}
	return &this
}

// NewNotFoundDataWithDefaults instantiates a new NotFoundData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotFoundDataWithDefaults() *NotFoundData {
	this := NotFoundData{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NotFoundData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotFoundData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NotFoundData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NotFoundData) SetMessage(v string) {
	o.Message = &v
}

func (o NotFoundData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotFoundData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotFoundData) UnmarshalJSON(data []byte) (err error) {
	varNotFoundData := _NotFoundData{}

	err = json.Unmarshal(data, &varNotFoundData)

	if err != nil {
		return err
	}

	*o = NotFoundData(varNotFoundData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotFoundData struct {
	value *NotFoundData
	isSet bool
}

func (v NullableNotFoundData) Get() *NotFoundData {
	return v.value
}

func (v *NullableNotFoundData) Set(val *NotFoundData) {
	v.value = val
	v.isSet = true
}

func (v NullableNotFoundData) IsSet() bool {
	return v.isSet
}

func (v *NullableNotFoundData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotFoundData(val *NotFoundData) *NullableNotFoundData {
	return &NullableNotFoundData{value: val, isSet: true}
}

func (v NullableNotFoundData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotFoundData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


