/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the UnauthorizedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnauthorizedData{}

// UnauthorizedData Unauthorized
type UnauthorizedData struct {
	// Error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UnauthorizedData UnauthorizedData

// NewUnauthorizedData instantiates a new UnauthorizedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnauthorizedData() *UnauthorizedData {
	this := UnauthorizedData{}
	return &this
}

// NewUnauthorizedDataWithDefaults instantiates a new UnauthorizedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnauthorizedDataWithDefaults() *UnauthorizedData {
	this := UnauthorizedData{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UnauthorizedData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnauthorizedData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UnauthorizedData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UnauthorizedData) SetMessage(v string) {
	o.Message = &v
}

func (o UnauthorizedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnauthorizedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnauthorizedData) UnmarshalJSON(data []byte) (err error) {
	varUnauthorizedData := _UnauthorizedData{}

	err = json.Unmarshal(data, &varUnauthorizedData)

	if err != nil {
		return err
	}

	*o = UnauthorizedData(varUnauthorizedData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnauthorizedData struct {
	value *UnauthorizedData
	isSet bool
}

func (v NullableUnauthorizedData) Get() *UnauthorizedData {
	return v.value
}

func (v *NullableUnauthorizedData) Set(val *UnauthorizedData) {
	v.value = val
	v.isSet = true
}

func (v NullableUnauthorizedData) IsSet() bool {
	return v.isSet
}

func (v *NullableUnauthorizedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnauthorizedData(val *UnauthorizedData) *NullableUnauthorizedData {
	return &NullableUnauthorizedData{value: val, isSet: true}
}

func (v NullableUnauthorizedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnauthorizedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


