/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the NotFoundStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotFoundStatus{}

// NotFoundStatus Resource Not Found
type NotFoundStatus struct {
	// HTTP status error code
	Code *int64 `json:"code,omitempty"`
	// HTTP status error text
	Text *string `json:"text,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotFoundStatus NotFoundStatus

// NewNotFoundStatus instantiates a new NotFoundStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotFoundStatus() *NotFoundStatus {
	this := NotFoundStatus{}
	return &this
}

// NewNotFoundStatusWithDefaults instantiates a new NotFoundStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotFoundStatusWithDefaults() *NotFoundStatus {
	this := NotFoundStatus{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NotFoundStatus) GetCode() int64 {
	if o == nil || IsNil(o.Code) {
		var ret int64
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotFoundStatus) GetCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NotFoundStatus) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int64 and assigns it to the Code field.
func (o *NotFoundStatus) SetCode(v int64) {
	o.Code = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *NotFoundStatus) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotFoundStatus) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *NotFoundStatus) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *NotFoundStatus) SetText(v string) {
	o.Text = &v
}

func (o NotFoundStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotFoundStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotFoundStatus) UnmarshalJSON(data []byte) (err error) {
	varNotFoundStatus := _NotFoundStatus{}

	err = json.Unmarshal(data, &varNotFoundStatus)

	if err != nil {
		return err
	}

	*o = NotFoundStatus(varNotFoundStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotFoundStatus struct {
	value *NotFoundStatus
	isSet bool
}

func (v NullableNotFoundStatus) Get() *NotFoundStatus {
	return v.value
}

func (v *NullableNotFoundStatus) Set(val *NotFoundStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNotFoundStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNotFoundStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotFoundStatus(val *NotFoundStatus) *NullableNotFoundStatus {
	return &NullableNotFoundStatus{value: val, isSet: true}
}

func (v NullableNotFoundStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotFoundStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


