/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
	"fmt"
)

// BundleTypeId The ID of the bundle type.
type BundleTypeId int64

// List of bundleTypeId
const (
	_1 BundleTypeId = 1
	_2 BundleTypeId = 2
	_3 BundleTypeId = 3
	_4 BundleTypeId = 4
)

// All allowed values of BundleTypeId enum
var AllowedBundleTypeIdEnumValues = []BundleTypeId{
	1,
	2,
	3,
	4,
}

func (v *BundleTypeId) UnmarshalJSON(src []byte) error {
	var value int64
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BundleTypeId(value)
	for _, existing := range AllowedBundleTypeIdEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BundleTypeId", value)
}

// NewBundleTypeIdFromValue returns a pointer to a valid BundleTypeId
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBundleTypeIdFromValue(v int64) (*BundleTypeId, error) {
	ev := BundleTypeId(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BundleTypeId: valid values are %v", v, AllowedBundleTypeIdEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BundleTypeId) IsValid() bool {
	for _, existing := range AllowedBundleTypeIdEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to bundleTypeId value
func (v BundleTypeId) Ptr() *BundleTypeId {
	return &v
}

type NullableBundleTypeId struct {
	value *BundleTypeId
	isSet bool
}

func (v NullableBundleTypeId) Get() *BundleTypeId {
	return v.value
}

func (v *NullableBundleTypeId) Set(val *BundleTypeId) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleTypeId) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleTypeId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleTypeId(val *BundleTypeId) *NullableBundleTypeId {
	return &NullableBundleTypeId{value: val, isSet: true}
}

func (v NullableBundleTypeId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleTypeId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

