/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the Unauthorized type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Unauthorized{}

// Unauthorized Unauthorized
type Unauthorized struct {
	Status *UnauthorizedStatus `json:"status,omitempty"`
	Data *UnauthorizedData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Unauthorized Unauthorized

// NewUnauthorized instantiates a new Unauthorized object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnauthorized() *Unauthorized {
	this := Unauthorized{}
	return &this
}

// NewUnauthorizedWithDefaults instantiates a new Unauthorized object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnauthorizedWithDefaults() *Unauthorized {
	this := Unauthorized{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Unauthorized) GetStatus() UnauthorizedStatus {
	if o == nil || IsNil(o.Status) {
		var ret UnauthorizedStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unauthorized) GetStatusOk() (*UnauthorizedStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Unauthorized) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given UnauthorizedStatus and assigns it to the Status field.
func (o *Unauthorized) SetStatus(v UnauthorizedStatus) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Unauthorized) GetData() UnauthorizedData {
	if o == nil || IsNil(o.Data) {
		var ret UnauthorizedData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Unauthorized) GetDataOk() (*UnauthorizedData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Unauthorized) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given UnauthorizedData and assigns it to the Data field.
func (o *Unauthorized) SetData(v UnauthorizedData) {
	o.Data = &v
}

func (o Unauthorized) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Unauthorized) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Unauthorized) UnmarshalJSON(data []byte) (err error) {
	varUnauthorized := _Unauthorized{}

	err = json.Unmarshal(data, &varUnauthorized)

	if err != nil {
		return err
	}

	*o = Unauthorized(varUnauthorized)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnauthorized struct {
	value *Unauthorized
	isSet bool
}

func (v NullableUnauthorized) Get() *Unauthorized {
	return v.value
}

func (v *NullableUnauthorized) Set(val *Unauthorized) {
	v.value = val
	v.isSet = true
}

func (v NullableUnauthorized) IsSet() bool {
	return v.isSet
}

func (v *NullableUnauthorized) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnauthorized(val *Unauthorized) *NullableUnauthorized {
	return &NullableUnauthorized{value: val, isSet: true}
}

func (v NullableUnauthorized) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnauthorized) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


