/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the ForbiddenStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForbiddenStatus{}

// ForbiddenStatus Forbidden
type ForbiddenStatus struct {
	// HTTP status error code
	Code *int64 `json:"code,omitempty"`
	// HTTP status error text
	Text *string `json:"text,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ForbiddenStatus ForbiddenStatus

// NewForbiddenStatus instantiates a new ForbiddenStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForbiddenStatus() *ForbiddenStatus {
	this := ForbiddenStatus{}
	return &this
}

// NewForbiddenStatusWithDefaults instantiates a new ForbiddenStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForbiddenStatusWithDefaults() *ForbiddenStatus {
	this := ForbiddenStatus{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ForbiddenStatus) GetCode() int64 {
	if o == nil || IsNil(o.Code) {
		var ret int64
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenStatus) GetCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ForbiddenStatus) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int64 and assigns it to the Code field.
func (o *ForbiddenStatus) SetCode(v int64) {
	o.Code = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ForbiddenStatus) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenStatus) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ForbiddenStatus) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ForbiddenStatus) SetText(v string) {
	o.Text = &v
}

func (o ForbiddenStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForbiddenStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ForbiddenStatus) UnmarshalJSON(data []byte) (err error) {
	varForbiddenStatus := _ForbiddenStatus{}

	err = json.Unmarshal(data, &varForbiddenStatus)

	if err != nil {
		return err
	}

	*o = ForbiddenStatus(varForbiddenStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "text")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableForbiddenStatus struct {
	value *ForbiddenStatus
	isSet bool
}

func (v NullableForbiddenStatus) Get() *ForbiddenStatus {
	return v.value
}

func (v *NullableForbiddenStatus) Set(val *ForbiddenStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableForbiddenStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableForbiddenStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForbiddenStatus(val *ForbiddenStatus) *NullableForbiddenStatus {
	return &NullableForbiddenStatus{value: val, isSet: true}
}

func (v NullableForbiddenStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForbiddenStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


