/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the ForbiddenData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForbiddenData{}

// ForbiddenData Forbidden
type ForbiddenData struct {
	// Error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ForbiddenData ForbiddenData

// NewForbiddenData instantiates a new ForbiddenData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForbiddenData() *ForbiddenData {
	this := ForbiddenData{}
	return &this
}

// NewForbiddenDataWithDefaults instantiates a new ForbiddenData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForbiddenDataWithDefaults() *ForbiddenData {
	this := ForbiddenData{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ForbiddenData) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForbiddenData) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ForbiddenData) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ForbiddenData) SetMessage(v string) {
	o.Message = &v
}

func (o ForbiddenData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForbiddenData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ForbiddenData) UnmarshalJSON(data []byte) (err error) {
	varForbiddenData := _ForbiddenData{}

	err = json.Unmarshal(data, &varForbiddenData)

	if err != nil {
		return err
	}

	*o = ForbiddenData(varForbiddenData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableForbiddenData struct {
	value *ForbiddenData
	isSet bool
}

func (v NullableForbiddenData) Get() *ForbiddenData {
	return v.value
}

func (v *NullableForbiddenData) Set(val *ForbiddenData) {
	v.value = val
	v.isSet = true
}

func (v NullableForbiddenData) IsSet() bool {
	return v.isSet
}

func (v *NullableForbiddenData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForbiddenData(val *ForbiddenData) *NullableForbiddenData {
	return &NullableForbiddenData{value: val, isSet: true}
}

func (v NullableForbiddenData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForbiddenData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


