/*
Cisco Secure Access Content Categories API

Get the Content Category settings in the Secure Access organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package contentcategories

import (
	"encoding/json"
)

// checks if the ContentCategorySetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentCategorySetting{}

// ContentCategorySetting The properties of the Content Category settings.
type ContentCategorySetting struct {
	// The ID of the Content Category setting.
	Id *int64 `json:"id,omitempty"`
	// The ID of the organization.
	OrganizationId *int64 `json:"organizationId,omitempty"`
	// Specifies whether the setting is the default setting.
	IsDefault *bool `json:"isDefault,omitempty"`
	// The name of the Content Category setting.
	Name *string `json:"name,omitempty"`
	// The number of bits in the Content Category.
	CategoryBits *string `json:"categoryBits,omitempty"`
	// The type of the Content Category setting.
	Type *string `json:"type,omitempty"`
	// The date and time (in seconds since the Unix Epoch) when the system created the Content Category setting.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// The date and time (in seconds since the Unix Epoch) when the system modified the Content Category setting.
	ModifiedAt *int64 `json:"modifiedAt,omitempty"`
	// Specifies whether the system marks the setting for deletion.
	MarkedForDeletion *bool `json:"markedForDeletion,omitempty"`
	BundleTypeId *BundleTypeId `json:"bundleTypeId,omitempty"`
	// Specifies whether the Security profile for the secure web gateway (SWG) is the default Security profile.
	IsSwgDefault *bool `json:"isSwgDefault,omitempty"`
	// The number of bits in Content Category for a Warn action.
	WarnCategoryBits *string `json:"warnCategoryBits,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ContentCategorySetting ContentCategorySetting

// NewContentCategorySetting instantiates a new ContentCategorySetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentCategorySetting() *ContentCategorySetting {
	this := ContentCategorySetting{}
	return &this
}

// NewContentCategorySettingWithDefaults instantiates a new ContentCategorySetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentCategorySettingWithDefaults() *ContentCategorySetting {
	this := ContentCategorySetting{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ContentCategorySetting) SetId(v int64) {
	o.Id = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int64
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetOrganizationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int64 and assigns it to the OrganizationId field.
func (o *ContentCategorySetting) SetOrganizationId(v int64) {
	o.OrganizationId = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *ContentCategorySetting) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContentCategorySetting) SetName(v string) {
	o.Name = &v
}

// GetCategoryBits returns the CategoryBits field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetCategoryBits() string {
	if o == nil || IsNil(o.CategoryBits) {
		var ret string
		return ret
	}
	return *o.CategoryBits
}

// GetCategoryBitsOk returns a tuple with the CategoryBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetCategoryBitsOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryBits) {
		return nil, false
	}
	return o.CategoryBits, true
}

// HasCategoryBits returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasCategoryBits() bool {
	if o != nil && !IsNil(o.CategoryBits) {
		return true
	}

	return false
}

// SetCategoryBits gets a reference to the given string and assigns it to the CategoryBits field.
func (o *ContentCategorySetting) SetCategoryBits(v string) {
	o.CategoryBits = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ContentCategorySetting) SetType(v string) {
	o.Type = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *ContentCategorySetting) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetModifiedAt() int64 {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret int64
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetModifiedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given int64 and assigns it to the ModifiedAt field.
func (o *ContentCategorySetting) SetModifiedAt(v int64) {
	o.ModifiedAt = &v
}

// GetMarkedForDeletion returns the MarkedForDeletion field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetMarkedForDeletion() bool {
	if o == nil || IsNil(o.MarkedForDeletion) {
		var ret bool
		return ret
	}
	return *o.MarkedForDeletion
}

// GetMarkedForDeletionOk returns a tuple with the MarkedForDeletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetMarkedForDeletionOk() (*bool, bool) {
	if o == nil || IsNil(o.MarkedForDeletion) {
		return nil, false
	}
	return o.MarkedForDeletion, true
}

// HasMarkedForDeletion returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasMarkedForDeletion() bool {
	if o != nil && !IsNil(o.MarkedForDeletion) {
		return true
	}

	return false
}

// SetMarkedForDeletion gets a reference to the given bool and assigns it to the MarkedForDeletion field.
func (o *ContentCategorySetting) SetMarkedForDeletion(v bool) {
	o.MarkedForDeletion = &v
}

// GetBundleTypeId returns the BundleTypeId field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetBundleTypeId() BundleTypeId {
	if o == nil || IsNil(o.BundleTypeId) {
		var ret BundleTypeId
		return ret
	}
	return *o.BundleTypeId
}

// GetBundleTypeIdOk returns a tuple with the BundleTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetBundleTypeIdOk() (*BundleTypeId, bool) {
	if o == nil || IsNil(o.BundleTypeId) {
		return nil, false
	}
	return o.BundleTypeId, true
}

// HasBundleTypeId returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasBundleTypeId() bool {
	if o != nil && !IsNil(o.BundleTypeId) {
		return true
	}

	return false
}

// SetBundleTypeId gets a reference to the given BundleTypeId and assigns it to the BundleTypeId field.
func (o *ContentCategorySetting) SetBundleTypeId(v BundleTypeId) {
	o.BundleTypeId = &v
}

// GetIsSwgDefault returns the IsSwgDefault field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetIsSwgDefault() bool {
	if o == nil || IsNil(o.IsSwgDefault) {
		var ret bool
		return ret
	}
	return *o.IsSwgDefault
}

// GetIsSwgDefaultOk returns a tuple with the IsSwgDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetIsSwgDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSwgDefault) {
		return nil, false
	}
	return o.IsSwgDefault, true
}

// HasIsSwgDefault returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasIsSwgDefault() bool {
	if o != nil && !IsNil(o.IsSwgDefault) {
		return true
	}

	return false
}

// SetIsSwgDefault gets a reference to the given bool and assigns it to the IsSwgDefault field.
func (o *ContentCategorySetting) SetIsSwgDefault(v bool) {
	o.IsSwgDefault = &v
}

// GetWarnCategoryBits returns the WarnCategoryBits field value if set, zero value otherwise.
func (o *ContentCategorySetting) GetWarnCategoryBits() string {
	if o == nil || IsNil(o.WarnCategoryBits) {
		var ret string
		return ret
	}
	return *o.WarnCategoryBits
}

// GetWarnCategoryBitsOk returns a tuple with the WarnCategoryBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentCategorySetting) GetWarnCategoryBitsOk() (*string, bool) {
	if o == nil || IsNil(o.WarnCategoryBits) {
		return nil, false
	}
	return o.WarnCategoryBits, true
}

// HasWarnCategoryBits returns a boolean if a field has been set.
func (o *ContentCategorySetting) HasWarnCategoryBits() bool {
	if o != nil && !IsNil(o.WarnCategoryBits) {
		return true
	}

	return false
}

// SetWarnCategoryBits gets a reference to the given string and assigns it to the WarnCategoryBits field.
func (o *ContentCategorySetting) SetWarnCategoryBits(v string) {
	o.WarnCategoryBits = &v
}

func (o ContentCategorySetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentCategorySetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CategoryBits) {
		toSerialize["categoryBits"] = o.CategoryBits
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	if !IsNil(o.MarkedForDeletion) {
		toSerialize["markedForDeletion"] = o.MarkedForDeletion
	}
	if !IsNil(o.BundleTypeId) {
		toSerialize["bundleTypeId"] = o.BundleTypeId
	}
	if !IsNil(o.IsSwgDefault) {
		toSerialize["isSwgDefault"] = o.IsSwgDefault
	}
	if !IsNil(o.WarnCategoryBits) {
		toSerialize["warnCategoryBits"] = o.WarnCategoryBits
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContentCategorySetting) UnmarshalJSON(data []byte) (err error) {
	varContentCategorySetting := _ContentCategorySetting{}

	err = json.Unmarshal(data, &varContentCategorySetting)

	if err != nil {
		return err
	}

	*o = ContentCategorySetting(varContentCategorySetting)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "isDefault")
		delete(additionalProperties, "name")
		delete(additionalProperties, "categoryBits")
		delete(additionalProperties, "type")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		delete(additionalProperties, "markedForDeletion")
		delete(additionalProperties, "bundleTypeId")
		delete(additionalProperties, "isSwgDefault")
		delete(additionalProperties, "warnCategoryBits")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContentCategorySetting struct {
	value *ContentCategorySetting
	isSet bool
}

func (v NullableContentCategorySetting) Get() *ContentCategorySetting {
	return v.value
}

func (v *NullableContentCategorySetting) Set(val *ContentCategorySetting) {
	v.value = val
	v.isSet = true
}

func (v NullableContentCategorySetting) IsSet() bool {
	return v.isSet
}

func (v *NullableContentCategorySetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentCategorySetting(val *ContentCategorySetting) *NullableContentCategorySetting {
	return &NullableContentCategorySetting{value: val, isSet: true}
}

func (v NullableContentCategorySetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentCategorySetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


