/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the UpdateAlertRulesStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRulesStatus200Response{}

// UpdateAlertRulesStatus200Response The properties of the updated status of the alert rules.
type UpdateAlertRulesStatus200Response struct {
	// Specifies whether the operation succeeded. Returns false if any ID is invalid.
	Success *bool `json:"success,omitempty"`
	// The list of IDs for the alert rules that the system updated.
	SuccessfulIds []int64 `json:"successfulIds,omitempty"`
	// The list of unique identifiers that either do no exist or the system failed to delete or update.
	ErrorIds []int64 `json:"errorIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAlertRulesStatus200Response UpdateAlertRulesStatus200Response

// NewUpdateAlertRulesStatus200Response instantiates a new UpdateAlertRulesStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertRulesStatus200Response() *UpdateAlertRulesStatus200Response {
	this := UpdateAlertRulesStatus200Response{}
	return &this
}

// NewUpdateAlertRulesStatus200ResponseWithDefaults instantiates a new UpdateAlertRulesStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertRulesStatus200ResponseWithDefaults() *UpdateAlertRulesStatus200Response {
	this := UpdateAlertRulesStatus200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateAlertRulesStatus200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertRulesStatus200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateAlertRulesStatus200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateAlertRulesStatus200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetSuccessfulIds returns the SuccessfulIds field value if set, zero value otherwise.
func (o *UpdateAlertRulesStatus200Response) GetSuccessfulIds() []int64 {
	if o == nil || IsNil(o.SuccessfulIds) {
		var ret []int64
		return ret
	}
	return o.SuccessfulIds
}

// GetSuccessfulIdsOk returns a tuple with the SuccessfulIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertRulesStatus200Response) GetSuccessfulIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.SuccessfulIds) {
		return nil, false
	}
	return o.SuccessfulIds, true
}

// HasSuccessfulIds returns a boolean if a field has been set.
func (o *UpdateAlertRulesStatus200Response) HasSuccessfulIds() bool {
	if o != nil && !IsNil(o.SuccessfulIds) {
		return true
	}

	return false
}

// SetSuccessfulIds gets a reference to the given []int64 and assigns it to the SuccessfulIds field.
func (o *UpdateAlertRulesStatus200Response) SetSuccessfulIds(v []int64) {
	o.SuccessfulIds = v
}

// GetErrorIds returns the ErrorIds field value if set, zero value otherwise.
func (o *UpdateAlertRulesStatus200Response) GetErrorIds() []int64 {
	if o == nil || IsNil(o.ErrorIds) {
		var ret []int64
		return ret
	}
	return o.ErrorIds
}

// GetErrorIdsOk returns a tuple with the ErrorIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertRulesStatus200Response) GetErrorIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.ErrorIds) {
		return nil, false
	}
	return o.ErrorIds, true
}

// HasErrorIds returns a boolean if a field has been set.
func (o *UpdateAlertRulesStatus200Response) HasErrorIds() bool {
	if o != nil && !IsNil(o.ErrorIds) {
		return true
	}

	return false
}

// SetErrorIds gets a reference to the given []int64 and assigns it to the ErrorIds field.
func (o *UpdateAlertRulesStatus200Response) SetErrorIds(v []int64) {
	o.ErrorIds = v
}

func (o UpdateAlertRulesStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertRulesStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.SuccessfulIds) {
		toSerialize["successfulIds"] = o.SuccessfulIds
	}
	if !IsNil(o.ErrorIds) {
		toSerialize["errorIds"] = o.ErrorIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAlertRulesStatus200Response) UnmarshalJSON(data []byte) (err error) {
	varUpdateAlertRulesStatus200Response := _UpdateAlertRulesStatus200Response{}

	err = json.Unmarshal(data, &varUpdateAlertRulesStatus200Response)

	if err != nil {
		return err
	}

	*o = UpdateAlertRulesStatus200Response(varUpdateAlertRulesStatus200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "successfulIds")
		delete(additionalProperties, "errorIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAlertRulesStatus200Response struct {
	value *UpdateAlertRulesStatus200Response
	isSet bool
}

func (v NullableUpdateAlertRulesStatus200Response) Get() *UpdateAlertRulesStatus200Response {
	return v.value
}

func (v *NullableUpdateAlertRulesStatus200Response) Set(val *UpdateAlertRulesStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertRulesStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertRulesStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertRulesStatus200Response(val *UpdateAlertRulesStatus200Response) *NullableUpdateAlertRulesStatus200Response {
	return &NullableUpdateAlertRulesStatus200Response{value: val, isSet: true}
}

func (v NullableUpdateAlertRulesStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertRulesStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


