/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"time"
)

// checks if the FiltersAlertObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiltersAlertObject{}

// FiltersAlertObject The properties of the filters query parameter. Filter for the attributes of the alerts.
type FiltersAlertObject struct {
	Status *StatusAlert `json:"status,omitempty"`
	Severity *SeverityAlert `json:"severity,omitempty"`
	// Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.
	CreatedAfter *time.Time `json:"created_after,omitempty"`
	// The time and date (ISO 8601 timestamp) when the system last modified the alert.
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// The name of the alert.
	AlertName *string `json:"alert_name,omitempty"`
	// Provide a search pattern to query for by the alert name, alert rule name, or alert rule category name.
	PatternSearch *string `json:"pattern_search,omitempty"`
	// Specify whether to query for the count of the active alerts only.
	OnlyActiveAlertsCount *bool `json:"only_active_alerts_count,omitempty"`
	TimeRange *TimeRange `json:"time_range,omitempty"`
	// Include the context field in each alert response. The context contains additional metadata about the alert.
	IncludeContext *bool `json:"include_context,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FiltersAlertObject FiltersAlertObject

// NewFiltersAlertObject instantiates a new FiltersAlertObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiltersAlertObject() *FiltersAlertObject {
	this := FiltersAlertObject{}
	var onlyActiveAlertsCount bool = false
	this.OnlyActiveAlertsCount = &onlyActiveAlertsCount
	var includeContext bool = false
	this.IncludeContext = &includeContext
	return &this
}

// NewFiltersAlertObjectWithDefaults instantiates a new FiltersAlertObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiltersAlertObjectWithDefaults() *FiltersAlertObject {
	this := FiltersAlertObject{}
	var onlyActiveAlertsCount bool = false
	this.OnlyActiveAlertsCount = &onlyActiveAlertsCount
	var includeContext bool = false
	this.IncludeContext = &includeContext
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetStatus() StatusAlert {
	if o == nil || IsNil(o.Status) {
		var ret StatusAlert
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetStatusOk() (*StatusAlert, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given StatusAlert and assigns it to the Status field.
func (o *FiltersAlertObject) SetStatus(v StatusAlert) {
	o.Status = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetSeverity() SeverityAlert {
	if o == nil || IsNil(o.Severity) {
		var ret SeverityAlert
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetSeverityOk() (*SeverityAlert, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given SeverityAlert and assigns it to the Severity field.
func (o *FiltersAlertObject) SetSeverity(v SeverityAlert) {
	o.Severity = &v
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetCreatedAfter() time.Time {
	if o == nil || IsNil(o.CreatedAfter) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAfter
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetCreatedAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAfter) {
		return nil, false
	}
	return o.CreatedAfter, true
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasCreatedAfter() bool {
	if o != nil && !IsNil(o.CreatedAfter) {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given time.Time and assigns it to the CreatedAfter field.
func (o *FiltersAlertObject) SetCreatedAfter(v time.Time) {
	o.CreatedAfter = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *FiltersAlertObject) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

// GetAlertName returns the AlertName field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetAlertName() string {
	if o == nil || IsNil(o.AlertName) {
		var ret string
		return ret
	}
	return *o.AlertName
}

// GetAlertNameOk returns a tuple with the AlertName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetAlertNameOk() (*string, bool) {
	if o == nil || IsNil(o.AlertName) {
		return nil, false
	}
	return o.AlertName, true
}

// HasAlertName returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasAlertName() bool {
	if o != nil && !IsNil(o.AlertName) {
		return true
	}

	return false
}

// SetAlertName gets a reference to the given string and assigns it to the AlertName field.
func (o *FiltersAlertObject) SetAlertName(v string) {
	o.AlertName = &v
}

// GetPatternSearch returns the PatternSearch field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetPatternSearch() string {
	if o == nil || IsNil(o.PatternSearch) {
		var ret string
		return ret
	}
	return *o.PatternSearch
}

// GetPatternSearchOk returns a tuple with the PatternSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetPatternSearchOk() (*string, bool) {
	if o == nil || IsNil(o.PatternSearch) {
		return nil, false
	}
	return o.PatternSearch, true
}

// HasPatternSearch returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasPatternSearch() bool {
	if o != nil && !IsNil(o.PatternSearch) {
		return true
	}

	return false
}

// SetPatternSearch gets a reference to the given string and assigns it to the PatternSearch field.
func (o *FiltersAlertObject) SetPatternSearch(v string) {
	o.PatternSearch = &v
}

// GetOnlyActiveAlertsCount returns the OnlyActiveAlertsCount field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetOnlyActiveAlertsCount() bool {
	if o == nil || IsNil(o.OnlyActiveAlertsCount) {
		var ret bool
		return ret
	}
	return *o.OnlyActiveAlertsCount
}

// GetOnlyActiveAlertsCountOk returns a tuple with the OnlyActiveAlertsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetOnlyActiveAlertsCountOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyActiveAlertsCount) {
		return nil, false
	}
	return o.OnlyActiveAlertsCount, true
}

// HasOnlyActiveAlertsCount returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasOnlyActiveAlertsCount() bool {
	if o != nil && !IsNil(o.OnlyActiveAlertsCount) {
		return true
	}

	return false
}

// SetOnlyActiveAlertsCount gets a reference to the given bool and assigns it to the OnlyActiveAlertsCount field.
func (o *FiltersAlertObject) SetOnlyActiveAlertsCount(v bool) {
	o.OnlyActiveAlertsCount = &v
}

// GetTimeRange returns the TimeRange field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetTimeRange() TimeRange {
	if o == nil || IsNil(o.TimeRange) {
		var ret TimeRange
		return ret
	}
	return *o.TimeRange
}

// GetTimeRangeOk returns a tuple with the TimeRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetTimeRangeOk() (*TimeRange, bool) {
	if o == nil || IsNil(o.TimeRange) {
		return nil, false
	}
	return o.TimeRange, true
}

// HasTimeRange returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasTimeRange() bool {
	if o != nil && !IsNil(o.TimeRange) {
		return true
	}

	return false
}

// SetTimeRange gets a reference to the given TimeRange and assigns it to the TimeRange field.
func (o *FiltersAlertObject) SetTimeRange(v TimeRange) {
	o.TimeRange = &v
}

// GetIncludeContext returns the IncludeContext field value if set, zero value otherwise.
func (o *FiltersAlertObject) GetIncludeContext() bool {
	if o == nil || IsNil(o.IncludeContext) {
		var ret bool
		return ret
	}
	return *o.IncludeContext
}

// GetIncludeContextOk returns a tuple with the IncludeContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiltersAlertObject) GetIncludeContextOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeContext) {
		return nil, false
	}
	return o.IncludeContext, true
}

// HasIncludeContext returns a boolean if a field has been set.
func (o *FiltersAlertObject) HasIncludeContext() bool {
	if o != nil && !IsNil(o.IncludeContext) {
		return true
	}

	return false
}

// SetIncludeContext gets a reference to the given bool and assigns it to the IncludeContext field.
func (o *FiltersAlertObject) SetIncludeContext(v bool) {
	o.IncludeContext = &v
}

func (o FiltersAlertObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiltersAlertObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.CreatedAfter) {
		toSerialize["created_after"] = o.CreatedAfter
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modified_at"] = o.ModifiedAt
	}
	if !IsNil(o.AlertName) {
		toSerialize["alert_name"] = o.AlertName
	}
	if !IsNil(o.PatternSearch) {
		toSerialize["pattern_search"] = o.PatternSearch
	}
	if !IsNil(o.OnlyActiveAlertsCount) {
		toSerialize["only_active_alerts_count"] = o.OnlyActiveAlertsCount
	}
	if !IsNil(o.TimeRange) {
		toSerialize["time_range"] = o.TimeRange
	}
	if !IsNil(o.IncludeContext) {
		toSerialize["include_context"] = o.IncludeContext
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FiltersAlertObject) UnmarshalJSON(data []byte) (err error) {
	varFiltersAlertObject := _FiltersAlertObject{}

	err = json.Unmarshal(data, &varFiltersAlertObject)

	if err != nil {
		return err
	}

	*o = FiltersAlertObject(varFiltersAlertObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "created_after")
		delete(additionalProperties, "modified_at")
		delete(additionalProperties, "alert_name")
		delete(additionalProperties, "pattern_search")
		delete(additionalProperties, "only_active_alerts_count")
		delete(additionalProperties, "time_range")
		delete(additionalProperties, "include_context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFiltersAlertObject struct {
	value *FiltersAlertObject
	isSet bool
}

func (v NullableFiltersAlertObject) Get() *FiltersAlertObject {
	return v.value
}

func (v *NullableFiltersAlertObject) Set(val *FiltersAlertObject) {
	v.value = val
	v.isSet = true
}

func (v NullableFiltersAlertObject) IsSet() bool {
	return v.isSet
}

func (v *NullableFiltersAlertObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiltersAlertObject(val *FiltersAlertObject) *NullableFiltersAlertObject {
	return &NullableFiltersAlertObject{value: val, isSet: true}
}

func (v NullableFiltersAlertObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiltersAlertObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


