/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAlertRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAlertRuleRequest{}

// CreateAlertRuleRequest The properties of the alert rule used by the system to create an alert rule.
type CreateAlertRuleRequest struct {
	// The unique name of the alert rule.
	Name string `json:"name"`
	// The description of the alert rule.
	Description *string `json:"description,omitempty"`
	Severity SeverityAlert `json:"severity"`
	Status StatusAlertRule `json:"status"`
	// The identifier of the rule type.  **Category: Connectivity**  | Rule Type ID | Rule Type Name | | --- | --- | | 1 | Network tunnel group disconnected | | 2 | No traffic through network tunnel group |  **Category: API Anomalies**  | Rule Type ID | Rule Type Name | | --- | --- | | 3 | Too many requests to get an access token | | 4 | High percentage of API errors | | 5 | Large number of rate limit errors | | 6 | More than one client using an API credential | | 7 | Authentication failures | | 8 | Programmatic creation of more than one API credential |  **Category: Data Usage**  | Rule Type ID | Rule Type Name | | --- | --- | | 9 | Data usage approaching limit |  **Category: Access Rule Changes**  | Rule Type ID | Rule Type Name | | --- | --- | | 10 | Rule creation, deletion, changing or reordering |  **Category: Behavior Analytics**  | Rule Type ID | Rule Type Name | | --- | --- | | 11 | Impossible travel detected | | 12 | Bulk upload operations | | 13 | Bulk download operations | | 14 | Bulk delete operations | | 15 | DLP violation spike | | 16 | Upload from high-risk countries | | 17 | Upload to high-risk countries |
	RuleTypeId int64 `json:"rule_type_id"`
	// The list of notifications for the alert rule.
	NotificationInfo []NotificationInfoAlertRule `json:"notification_info,omitempty"`
	Conditions *ConditionsAlertRule `json:"conditions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAlertRuleRequest CreateAlertRuleRequest

// NewCreateAlertRuleRequest instantiates a new CreateAlertRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAlertRuleRequest(name string, severity SeverityAlert, status StatusAlertRule, ruleTypeId int64) *CreateAlertRuleRequest {
	this := CreateAlertRuleRequest{}
	this.Name = name
	this.Severity = severity
	this.Status = status
	this.RuleTypeId = ruleTypeId
	return &this
}

// NewCreateAlertRuleRequestWithDefaults instantiates a new CreateAlertRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAlertRuleRequestWithDefaults() *CreateAlertRuleRequest {
	this := CreateAlertRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAlertRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAlertRuleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateAlertRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateAlertRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateAlertRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSeverity returns the Severity field value
func (o *CreateAlertRuleRequest) GetSeverity() SeverityAlert {
	if o == nil {
		var ret SeverityAlert
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetSeverityOk() (*SeverityAlert, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *CreateAlertRuleRequest) SetSeverity(v SeverityAlert) {
	o.Severity = v
}

// GetStatus returns the Status field value
func (o *CreateAlertRuleRequest) GetStatus() StatusAlertRule {
	if o == nil {
		var ret StatusAlertRule
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetStatusOk() (*StatusAlertRule, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateAlertRuleRequest) SetStatus(v StatusAlertRule) {
	o.Status = v
}

// GetRuleTypeId returns the RuleTypeId field value
func (o *CreateAlertRuleRequest) GetRuleTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RuleTypeId
}

// GetRuleTypeIdOk returns a tuple with the RuleTypeId field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetRuleTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuleTypeId, true
}

// SetRuleTypeId sets field value
func (o *CreateAlertRuleRequest) SetRuleTypeId(v int64) {
	o.RuleTypeId = v
}

// GetNotificationInfo returns the NotificationInfo field value if set, zero value otherwise.
func (o *CreateAlertRuleRequest) GetNotificationInfo() []NotificationInfoAlertRule {
	if o == nil || IsNil(o.NotificationInfo) {
		var ret []NotificationInfoAlertRule
		return ret
	}
	return o.NotificationInfo
}

// GetNotificationInfoOk returns a tuple with the NotificationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetNotificationInfoOk() ([]NotificationInfoAlertRule, bool) {
	if o == nil || IsNil(o.NotificationInfo) {
		return nil, false
	}
	return o.NotificationInfo, true
}

// HasNotificationInfo returns a boolean if a field has been set.
func (o *CreateAlertRuleRequest) HasNotificationInfo() bool {
	if o != nil && !IsNil(o.NotificationInfo) {
		return true
	}

	return false
}

// SetNotificationInfo gets a reference to the given []NotificationInfoAlertRule and assigns it to the NotificationInfo field.
func (o *CreateAlertRuleRequest) SetNotificationInfo(v []NotificationInfoAlertRule) {
	o.NotificationInfo = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CreateAlertRuleRequest) GetConditions() ConditionsAlertRule {
	if o == nil || IsNil(o.Conditions) {
		var ret ConditionsAlertRule
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRuleRequest) GetConditionsOk() (*ConditionsAlertRule, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CreateAlertRuleRequest) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given ConditionsAlertRule and assigns it to the Conditions field.
func (o *CreateAlertRuleRequest) SetConditions(v ConditionsAlertRule) {
	o.Conditions = &v
}

func (o CreateAlertRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAlertRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["severity"] = o.Severity
	toSerialize["status"] = o.Status
	toSerialize["rule_type_id"] = o.RuleTypeId
	if !IsNil(o.NotificationInfo) {
		toSerialize["notification_info"] = o.NotificationInfo
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAlertRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"severity",
		"status",
		"rule_type_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAlertRuleRequest := _CreateAlertRuleRequest{}

	err = json.Unmarshal(data, &varCreateAlertRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateAlertRuleRequest(varCreateAlertRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "status")
		delete(additionalProperties, "rule_type_id")
		delete(additionalProperties, "notification_info")
		delete(additionalProperties, "conditions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAlertRuleRequest struct {
	value *CreateAlertRuleRequest
	isSet bool
}

func (v NullableCreateAlertRuleRequest) Get() *CreateAlertRuleRequest {
	return v.value
}

func (v *NullableCreateAlertRuleRequest) Set(val *CreateAlertRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRuleRequest(val *CreateAlertRuleRequest) *NullableCreateAlertRuleRequest {
	return &NullableCreateAlertRuleRequest{value: val, isSet: true}
}

func (v NullableCreateAlertRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


