/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the UpdateAlertRule200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRule200Response{}

// UpdateAlertRule200Response The properties of the updated alert rule.
type UpdateAlertRule200Response struct {
	// The message from the system about the update of the alert rule.
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAlertRule200Response UpdateAlertRule200Response

// NewUpdateAlertRule200Response instantiates a new UpdateAlertRule200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertRule200Response() *UpdateAlertRule200Response {
	this := UpdateAlertRule200Response{}
	return &this
}

// NewUpdateAlertRule200ResponseWithDefaults instantiates a new UpdateAlertRule200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertRule200ResponseWithDefaults() *UpdateAlertRule200Response {
	this := UpdateAlertRule200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateAlertRule200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertRule200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateAlertRule200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateAlertRule200Response) SetMessage(v string) {
	o.Message = &v
}

func (o UpdateAlertRule200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertRule200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAlertRule200Response) UnmarshalJSON(data []byte) (err error) {
	varUpdateAlertRule200Response := _UpdateAlertRule200Response{}

	err = json.Unmarshal(data, &varUpdateAlertRule200Response)

	if err != nil {
		return err
	}

	*o = UpdateAlertRule200Response(varUpdateAlertRule200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAlertRule200Response struct {
	value *UpdateAlertRule200Response
	isSet bool
}

func (v NullableUpdateAlertRule200Response) Get() *UpdateAlertRule200Response {
	return v.value
}

func (v *NullableUpdateAlertRule200Response) Set(val *UpdateAlertRule200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertRule200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertRule200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertRule200Response(val *UpdateAlertRule200Response) *NullableUpdateAlertRule200Response {
	return &NullableUpdateAlertRule200Response{value: val, isSet: true}
}

func (v NullableUpdateAlertRule200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertRule200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


