/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateAlertsStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertsStatusRequest{}

// UpdateAlertsStatusRequest The properties of the alerts used by the system to update the alerts.
type UpdateAlertsStatusRequest struct {
	// The numeric identifier of the alert status. Use `1` to enable the alert or `2` to disable the alert.
	Status int64 `json:"status"`
	// The list of identifiers used by the system to update the alerts.
	EntityIds []string `json:"entity_ids"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAlertsStatusRequest UpdateAlertsStatusRequest

// NewUpdateAlertsStatusRequest instantiates a new UpdateAlertsStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertsStatusRequest(status int64, entityIds []string) *UpdateAlertsStatusRequest {
	this := UpdateAlertsStatusRequest{}
	this.Status = status
	this.EntityIds = entityIds
	return &this
}

// NewUpdateAlertsStatusRequestWithDefaults instantiates a new UpdateAlertsStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertsStatusRequestWithDefaults() *UpdateAlertsStatusRequest {
	this := UpdateAlertsStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateAlertsStatusRequest) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertsStatusRequest) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateAlertsStatusRequest) SetStatus(v int64) {
	o.Status = v
}

// GetEntityIds returns the EntityIds field value
func (o *UpdateAlertsStatusRequest) GetEntityIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EntityIds
}

// GetEntityIdsOk returns a tuple with the EntityIds field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertsStatusRequest) GetEntityIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EntityIds, true
}

// SetEntityIds sets field value
func (o *UpdateAlertsStatusRequest) SetEntityIds(v []string) {
	o.EntityIds = v
}

func (o UpdateAlertsStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertsStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["entity_ids"] = o.EntityIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAlertsStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"entity_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAlertsStatusRequest := _UpdateAlertsStatusRequest{}

	err = json.Unmarshal(data, &varUpdateAlertsStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateAlertsStatusRequest(varUpdateAlertsStatusRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "entity_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAlertsStatusRequest struct {
	value *UpdateAlertsStatusRequest
	isSet bool
}

func (v NullableUpdateAlertsStatusRequest) Get() *UpdateAlertsStatusRequest {
	return v.value
}

func (v *NullableUpdateAlertsStatusRequest) Set(val *UpdateAlertsStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertsStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertsStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertsStatusRequest(val *UpdateAlertsStatusRequest) *NullableUpdateAlertsStatusRequest {
	return &NullableUpdateAlertsStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateAlertsStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertsStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


