/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the BehaviorAnalyticsContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BehaviorAnalyticsContext{}

// BehaviorAnalyticsContext The properties of the context for the Behavior Analytics (UEBA) alerts.
type BehaviorAnalyticsContext struct {
	// The URL for the entity in Secure Access.
	RedirectEntityUrl *string `json:"redirect_entity_url,omitempty"`
	// The label for the entity's redirect URL.
	RedirectEntityUrlLabel *string `json:"redirect_entity_url_label,omitempty"`
	// The URL for the UEBA event in Secure Access.
	RedirectEventUrl *string `json:"redirect_event_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BehaviorAnalyticsContext BehaviorAnalyticsContext

// NewBehaviorAnalyticsContext instantiates a new BehaviorAnalyticsContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBehaviorAnalyticsContext() *BehaviorAnalyticsContext {
	this := BehaviorAnalyticsContext{}
	return &this
}

// NewBehaviorAnalyticsContextWithDefaults instantiates a new BehaviorAnalyticsContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBehaviorAnalyticsContextWithDefaults() *BehaviorAnalyticsContext {
	this := BehaviorAnalyticsContext{}
	return &this
}

// GetRedirectEntityUrl returns the RedirectEntityUrl field value if set, zero value otherwise.
func (o *BehaviorAnalyticsContext) GetRedirectEntityUrl() string {
	if o == nil || IsNil(o.RedirectEntityUrl) {
		var ret string
		return ret
	}
	return *o.RedirectEntityUrl
}

// GetRedirectEntityUrlOk returns a tuple with the RedirectEntityUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BehaviorAnalyticsContext) GetRedirectEntityUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectEntityUrl) {
		return nil, false
	}
	return o.RedirectEntityUrl, true
}

// HasRedirectEntityUrl returns a boolean if a field has been set.
func (o *BehaviorAnalyticsContext) HasRedirectEntityUrl() bool {
	if o != nil && !IsNil(o.RedirectEntityUrl) {
		return true
	}

	return false
}

// SetRedirectEntityUrl gets a reference to the given string and assigns it to the RedirectEntityUrl field.
func (o *BehaviorAnalyticsContext) SetRedirectEntityUrl(v string) {
	o.RedirectEntityUrl = &v
}

// GetRedirectEntityUrlLabel returns the RedirectEntityUrlLabel field value if set, zero value otherwise.
func (o *BehaviorAnalyticsContext) GetRedirectEntityUrlLabel() string {
	if o == nil || IsNil(o.RedirectEntityUrlLabel) {
		var ret string
		return ret
	}
	return *o.RedirectEntityUrlLabel
}

// GetRedirectEntityUrlLabelOk returns a tuple with the RedirectEntityUrlLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BehaviorAnalyticsContext) GetRedirectEntityUrlLabelOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectEntityUrlLabel) {
		return nil, false
	}
	return o.RedirectEntityUrlLabel, true
}

// HasRedirectEntityUrlLabel returns a boolean if a field has been set.
func (o *BehaviorAnalyticsContext) HasRedirectEntityUrlLabel() bool {
	if o != nil && !IsNil(o.RedirectEntityUrlLabel) {
		return true
	}

	return false
}

// SetRedirectEntityUrlLabel gets a reference to the given string and assigns it to the RedirectEntityUrlLabel field.
func (o *BehaviorAnalyticsContext) SetRedirectEntityUrlLabel(v string) {
	o.RedirectEntityUrlLabel = &v
}

// GetRedirectEventUrl returns the RedirectEventUrl field value if set, zero value otherwise.
func (o *BehaviorAnalyticsContext) GetRedirectEventUrl() string {
	if o == nil || IsNil(o.RedirectEventUrl) {
		var ret string
		return ret
	}
	return *o.RedirectEventUrl
}

// GetRedirectEventUrlOk returns a tuple with the RedirectEventUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BehaviorAnalyticsContext) GetRedirectEventUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectEventUrl) {
		return nil, false
	}
	return o.RedirectEventUrl, true
}

// HasRedirectEventUrl returns a boolean if a field has been set.
func (o *BehaviorAnalyticsContext) HasRedirectEventUrl() bool {
	if o != nil && !IsNil(o.RedirectEventUrl) {
		return true
	}

	return false
}

// SetRedirectEventUrl gets a reference to the given string and assigns it to the RedirectEventUrl field.
func (o *BehaviorAnalyticsContext) SetRedirectEventUrl(v string) {
	o.RedirectEventUrl = &v
}

func (o BehaviorAnalyticsContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BehaviorAnalyticsContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RedirectEntityUrl) {
		toSerialize["redirect_entity_url"] = o.RedirectEntityUrl
	}
	if !IsNil(o.RedirectEntityUrlLabel) {
		toSerialize["redirect_entity_url_label"] = o.RedirectEntityUrlLabel
	}
	if !IsNil(o.RedirectEventUrl) {
		toSerialize["redirect_event_url"] = o.RedirectEventUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BehaviorAnalyticsContext) UnmarshalJSON(data []byte) (err error) {
	varBehaviorAnalyticsContext := _BehaviorAnalyticsContext{}

	err = json.Unmarshal(data, &varBehaviorAnalyticsContext)

	if err != nil {
		return err
	}

	*o = BehaviorAnalyticsContext(varBehaviorAnalyticsContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "redirect_entity_url")
		delete(additionalProperties, "redirect_entity_url_label")
		delete(additionalProperties, "redirect_event_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBehaviorAnalyticsContext struct {
	value *BehaviorAnalyticsContext
	isSet bool
}

func (v NullableBehaviorAnalyticsContext) Get() *BehaviorAnalyticsContext {
	return v.value
}

func (v *NullableBehaviorAnalyticsContext) Set(val *BehaviorAnalyticsContext) {
	v.value = val
	v.isSet = true
}

func (v NullableBehaviorAnalyticsContext) IsSet() bool {
	return v.isSet
}

func (v *NullableBehaviorAnalyticsContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBehaviorAnalyticsContext(val *BehaviorAnalyticsContext) *NullableBehaviorAnalyticsContext {
	return &NullableBehaviorAnalyticsContext{value: val, isSet: true}
}

func (v NullableBehaviorAnalyticsContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBehaviorAnalyticsContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


