/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// NotificationTypeAll The type of the notification for the alert rule.
type NotificationTypeAll string

// List of notificationTypeAll
const (
	NOTIFICATIONTYPEALL_EMAIL NotificationTypeAll = "email"
	NOTIFICATIONTYPEALL_WEBHOOK NotificationTypeAll = "webhook"
)

// All allowed values of NotificationTypeAll enum
var AllowedNotificationTypeAllEnumValues = []NotificationTypeAll{
	"email",
	"webhook",
}

func (v *NotificationTypeAll) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationTypeAll(value)
	for _, existing := range AllowedNotificationTypeAllEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationTypeAll", value)
}

// NewNotificationTypeAllFromValue returns a pointer to a valid NotificationTypeAll
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationTypeAllFromValue(v string) (*NotificationTypeAll, error) {
	ev := NotificationTypeAll(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationTypeAll: valid values are %v", v, AllowedNotificationTypeAllEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationTypeAll) IsValid() bool {
	for _, existing := range AllowedNotificationTypeAllEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to notificationTypeAll value
func (v NotificationTypeAll) Ptr() *NotificationTypeAll {
	return &v
}

type NullableNotificationTypeAll struct {
	value *NotificationTypeAll
	isSet bool
}

func (v NullableNotificationTypeAll) Get() *NotificationTypeAll {
	return v.value
}

func (v *NullableNotificationTypeAll) Set(val *NotificationTypeAll) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationTypeAll) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationTypeAll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationTypeAll(val *NotificationTypeAll) *NullableNotificationTypeAll {
	return &NullableNotificationTypeAll{value: val, isSet: true}
}

func (v NullableNotificationTypeAll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationTypeAll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

