/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the NotificationInfoAlertRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationInfoAlertRule{}

// NotificationInfoAlertRule The properties of the notification for the alert rule.
type NotificationInfoAlertRule struct {
	Type *NotificationTypeAll `json:"type,omitempty"`
	// The list of email recipients configured in the alert rule to receive the notification.
	Recipients []string `json:"recipients,omitempty"`
	// The list of unique identifiers for the Webhooks configured on the alert rule.
	WebhookIds []string `json:"webhook_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotificationInfoAlertRule NotificationInfoAlertRule

// NewNotificationInfoAlertRule instantiates a new NotificationInfoAlertRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationInfoAlertRule() *NotificationInfoAlertRule {
	this := NotificationInfoAlertRule{}
	return &this
}

// NewNotificationInfoAlertRuleWithDefaults instantiates a new NotificationInfoAlertRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationInfoAlertRuleWithDefaults() *NotificationInfoAlertRule {
	this := NotificationInfoAlertRule{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NotificationInfoAlertRule) GetType() NotificationTypeAll {
	if o == nil || IsNil(o.Type) {
		var ret NotificationTypeAll
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationInfoAlertRule) GetTypeOk() (*NotificationTypeAll, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NotificationInfoAlertRule) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given NotificationTypeAll and assigns it to the Type field.
func (o *NotificationInfoAlertRule) SetType(v NotificationTypeAll) {
	o.Type = &v
}

// GetRecipients returns the Recipients field value if set, zero value otherwise.
func (o *NotificationInfoAlertRule) GetRecipients() []string {
	if o == nil || IsNil(o.Recipients) {
		var ret []string
		return ret
	}
	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationInfoAlertRule) GetRecipientsOk() ([]string, bool) {
	if o == nil || IsNil(o.Recipients) {
		return nil, false
	}
	return o.Recipients, true
}

// HasRecipients returns a boolean if a field has been set.
func (o *NotificationInfoAlertRule) HasRecipients() bool {
	if o != nil && !IsNil(o.Recipients) {
		return true
	}

	return false
}

// SetRecipients gets a reference to the given []string and assigns it to the Recipients field.
func (o *NotificationInfoAlertRule) SetRecipients(v []string) {
	o.Recipients = v
}

// GetWebhookIds returns the WebhookIds field value if set, zero value otherwise.
func (o *NotificationInfoAlertRule) GetWebhookIds() []string {
	if o == nil || IsNil(o.WebhookIds) {
		var ret []string
		return ret
	}
	return o.WebhookIds
}

// GetWebhookIdsOk returns a tuple with the WebhookIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationInfoAlertRule) GetWebhookIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhookIds) {
		return nil, false
	}
	return o.WebhookIds, true
}

// HasWebhookIds returns a boolean if a field has been set.
func (o *NotificationInfoAlertRule) HasWebhookIds() bool {
	if o != nil && !IsNil(o.WebhookIds) {
		return true
	}

	return false
}

// SetWebhookIds gets a reference to the given []string and assigns it to the WebhookIds field.
func (o *NotificationInfoAlertRule) SetWebhookIds(v []string) {
	o.WebhookIds = v
}

func (o NotificationInfoAlertRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationInfoAlertRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Recipients) {
		toSerialize["recipients"] = o.Recipients
	}
	if !IsNil(o.WebhookIds) {
		toSerialize["webhook_ids"] = o.WebhookIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationInfoAlertRule) UnmarshalJSON(data []byte) (err error) {
	varNotificationInfoAlertRule := _NotificationInfoAlertRule{}

	err = json.Unmarshal(data, &varNotificationInfoAlertRule)

	if err != nil {
		return err
	}

	*o = NotificationInfoAlertRule(varNotificationInfoAlertRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "recipients")
		delete(additionalProperties, "webhook_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationInfoAlertRule struct {
	value *NotificationInfoAlertRule
	isSet bool
}

func (v NullableNotificationInfoAlertRule) Get() *NotificationInfoAlertRule {
	return v.value
}

func (v *NullableNotificationInfoAlertRule) Set(val *NotificationInfoAlertRule) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationInfoAlertRule) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationInfoAlertRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationInfoAlertRule(val *NotificationInfoAlertRule) *NullableNotificationInfoAlertRule {
	return &NullableNotificationInfoAlertRule{value: val, isSet: true}
}

func (v NullableNotificationInfoAlertRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationInfoAlertRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


