/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the CreateAlertRule429Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAlertRule429Response{}

// CreateAlertRule429Response struct for CreateAlertRule429Response
type CreateAlertRule429Response struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	// The HTTP status code returned in the response.
	Status *int64 `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAlertRule429Response CreateAlertRule429Response

// NewCreateAlertRule429Response instantiates a new CreateAlertRule429Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAlertRule429Response() *CreateAlertRule429Response {
	this := CreateAlertRule429Response{}
	return &this
}

// NewCreateAlertRule429ResponseWithDefaults instantiates a new CreateAlertRule429Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAlertRule429ResponseWithDefaults() *CreateAlertRule429Response {
	this := CreateAlertRule429Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateAlertRule429Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRule429Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateAlertRule429Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CreateAlertRule429Response) SetError(v string) {
	o.Error = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateAlertRule429Response) GetStatus() int64 {
	if o == nil || IsNil(o.Status) {
		var ret int64
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRule429Response) GetStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateAlertRule429Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int64 and assigns it to the Status field.
func (o *CreateAlertRule429Response) SetStatus(v int64) {
	o.Status = &v
}

func (o CreateAlertRule429Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAlertRule429Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAlertRule429Response) UnmarshalJSON(data []byte) (err error) {
	varCreateAlertRule429Response := _CreateAlertRule429Response{}

	err = json.Unmarshal(data, &varCreateAlertRule429Response)

	if err != nil {
		return err
	}

	*o = CreateAlertRule429Response(varCreateAlertRule429Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAlertRule429Response struct {
	value *CreateAlertRule429Response
	isSet bool
}

func (v NullableCreateAlertRule429Response) Get() *CreateAlertRule429Response {
	return v.value
}

func (v *NullableCreateAlertRule429Response) Set(val *CreateAlertRule429Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRule429Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRule429Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRule429Response(val *CreateAlertRule429Response) *NullableCreateAlertRule429Response {
	return &NullableCreateAlertRule429Response{value: val, isSet: true}
}

func (v NullableCreateAlertRule429Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRule429Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


