/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the ConditionsAlertRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConditionsAlertRule{}

// ConditionsAlertRule The conditions that trigger the type of notification.
type ConditionsAlertRule struct {
	// Choose from one of the accepted conditions: `all` (AND), `any` (OR), or ''.
	MatchType *string `json:"match_type,omitempty"`
	// The list of conditions that the system uses to evaluate the alert rule.
	Rows []ConditionsAlertRuleRowsInner `json:"rows,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ConditionsAlertRule ConditionsAlertRule

// NewConditionsAlertRule instantiates a new ConditionsAlertRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConditionsAlertRule() *ConditionsAlertRule {
	this := ConditionsAlertRule{}
	return &this
}

// NewConditionsAlertRuleWithDefaults instantiates a new ConditionsAlertRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionsAlertRuleWithDefaults() *ConditionsAlertRule {
	this := ConditionsAlertRule{}
	return &this
}

// GetMatchType returns the MatchType field value if set, zero value otherwise.
func (o *ConditionsAlertRule) GetMatchType() string {
	if o == nil || IsNil(o.MatchType) {
		var ret string
		return ret
	}
	return *o.MatchType
}

// GetMatchTypeOk returns a tuple with the MatchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConditionsAlertRule) GetMatchTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MatchType) {
		return nil, false
	}
	return o.MatchType, true
}

// HasMatchType returns a boolean if a field has been set.
func (o *ConditionsAlertRule) HasMatchType() bool {
	if o != nil && !IsNil(o.MatchType) {
		return true
	}

	return false
}

// SetMatchType gets a reference to the given string and assigns it to the MatchType field.
func (o *ConditionsAlertRule) SetMatchType(v string) {
	o.MatchType = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *ConditionsAlertRule) GetRows() []ConditionsAlertRuleRowsInner {
	if o == nil || IsNil(o.Rows) {
		var ret []ConditionsAlertRuleRowsInner
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConditionsAlertRule) GetRowsOk() ([]ConditionsAlertRuleRowsInner, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *ConditionsAlertRule) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []ConditionsAlertRuleRowsInner and assigns it to the Rows field.
func (o *ConditionsAlertRule) SetRows(v []ConditionsAlertRuleRowsInner) {
	o.Rows = v
}

func (o ConditionsAlertRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConditionsAlertRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MatchType) {
		toSerialize["match_type"] = o.MatchType
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConditionsAlertRule) UnmarshalJSON(data []byte) (err error) {
	varConditionsAlertRule := _ConditionsAlertRule{}

	err = json.Unmarshal(data, &varConditionsAlertRule)

	if err != nil {
		return err
	}

	*o = ConditionsAlertRule(varConditionsAlertRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "match_type")
		delete(additionalProperties, "rows")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConditionsAlertRule struct {
	value *ConditionsAlertRule
	isSet bool
}

func (v NullableConditionsAlertRule) Get() *ConditionsAlertRule {
	return v.value
}

func (v *NullableConditionsAlertRule) Set(val *ConditionsAlertRule) {
	v.value = val
	v.isSet = true
}

func (v NullableConditionsAlertRule) IsSet() bool {
	return v.isSet
}

func (v *NullableConditionsAlertRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConditionsAlertRule(val *ConditionsAlertRule) *NullableConditionsAlertRule {
	return &NullableConditionsAlertRule{value: val, isSet: true}
}

func (v NullableConditionsAlertRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConditionsAlertRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


