/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the ListAlertRules403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAlertRules403Response{}

// ListAlertRules403Response struct for ListAlertRules403Response
type ListAlertRules403Response struct {
	// Error message explaining the reason for failure.
	Error *string `json:"error,omitempty"`
	// The HTTP status code returned in the response.
	Status *int64 `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAlertRules403Response ListAlertRules403Response

// NewListAlertRules403Response instantiates a new ListAlertRules403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAlertRules403Response() *ListAlertRules403Response {
	this := ListAlertRules403Response{}
	return &this
}

// NewListAlertRules403ResponseWithDefaults instantiates a new ListAlertRules403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAlertRules403ResponseWithDefaults() *ListAlertRules403Response {
	this := ListAlertRules403Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ListAlertRules403Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlertRules403Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ListAlertRules403Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ListAlertRules403Response) SetError(v string) {
	o.Error = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListAlertRules403Response) GetStatus() int64 {
	if o == nil || IsNil(o.Status) {
		var ret int64
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlertRules403Response) GetStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListAlertRules403Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int64 and assigns it to the Status field.
func (o *ListAlertRules403Response) SetStatus(v int64) {
	o.Status = &v
}

func (o ListAlertRules403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAlertRules403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAlertRules403Response) UnmarshalJSON(data []byte) (err error) {
	varListAlertRules403Response := _ListAlertRules403Response{}

	err = json.Unmarshal(data, &varListAlertRules403Response)

	if err != nil {
		return err
	}

	*o = ListAlertRules403Response(varListAlertRules403Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAlertRules403Response struct {
	value *ListAlertRules403Response
	isSet bool
}

func (v NullableListAlertRules403Response) Get() *ListAlertRules403Response {
	return v.value
}

func (v *NullableListAlertRules403Response) Set(val *ListAlertRules403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlertRules403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlertRules403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlertRules403Response(val *ListAlertRules403Response) *NullableListAlertRules403Response {
	return &NullableListAlertRules403Response{value: val, isSet: true}
}

func (v NullableListAlertRules403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlertRules403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


