/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the ListAlertRules401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAlertRules401Response{}

// ListAlertRules401Response struct for ListAlertRules401Response
type ListAlertRules401Response struct {
	// Unauthorized
	Error *string `json:"error,omitempty"`
	// The HTTP status code returned in the response.
	Status *int64 `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListAlertRules401Response ListAlertRules401Response

// NewListAlertRules401Response instantiates a new ListAlertRules401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAlertRules401Response() *ListAlertRules401Response {
	this := ListAlertRules401Response{}
	return &this
}

// NewListAlertRules401ResponseWithDefaults instantiates a new ListAlertRules401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAlertRules401ResponseWithDefaults() *ListAlertRules401Response {
	this := ListAlertRules401Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ListAlertRules401Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlertRules401Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ListAlertRules401Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ListAlertRules401Response) SetError(v string) {
	o.Error = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListAlertRules401Response) GetStatus() int64 {
	if o == nil || IsNil(o.Status) {
		var ret int64
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAlertRules401Response) GetStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListAlertRules401Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int64 and assigns it to the Status field.
func (o *ListAlertRules401Response) SetStatus(v int64) {
	o.Status = &v
}

func (o ListAlertRules401Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAlertRules401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAlertRules401Response) UnmarshalJSON(data []byte) (err error) {
	varListAlertRules401Response := _ListAlertRules401Response{}

	err = json.Unmarshal(data, &varListAlertRules401Response)

	if err != nil {
		return err
	}

	*o = ListAlertRules401Response(varListAlertRules401Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAlertRules401Response struct {
	value *ListAlertRules401Response
	isSet bool
}

func (v NullableListAlertRules401Response) Get() *ListAlertRules401Response {
	return v.value
}

func (v *NullableListAlertRules401Response) Set(val *ListAlertRules401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlertRules401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlertRules401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlertRules401Response(val *ListAlertRules401Response) *NullableListAlertRules401Response {
	return &NullableListAlertRules401Response{value: val, isSet: true}
}

func (v NullableListAlertRules401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlertRules401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


