/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the CreateAlertRule201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAlertRule201Response{}

// CreateAlertRule201Response The properties of the created alert rule.
type CreateAlertRule201Response struct {
	// The message from the system about the creation of the alert rule.
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAlertRule201Response CreateAlertRule201Response

// NewCreateAlertRule201Response instantiates a new CreateAlertRule201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAlertRule201Response() *CreateAlertRule201Response {
	this := CreateAlertRule201Response{}
	return &this
}

// NewCreateAlertRule201ResponseWithDefaults instantiates a new CreateAlertRule201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAlertRule201ResponseWithDefaults() *CreateAlertRule201Response {
	this := CreateAlertRule201Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateAlertRule201Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRule201Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateAlertRule201Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateAlertRule201Response) SetMessage(v string) {
	o.Message = &v
}

func (o CreateAlertRule201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAlertRule201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAlertRule201Response) UnmarshalJSON(data []byte) (err error) {
	varCreateAlertRule201Response := _CreateAlertRule201Response{}

	err = json.Unmarshal(data, &varCreateAlertRule201Response)

	if err != nil {
		return err
	}

	*o = CreateAlertRule201Response(varCreateAlertRule201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAlertRule201Response struct {
	value *CreateAlertRule201Response
	isSet bool
}

func (v NullableCreateAlertRule201Response) Get() *CreateAlertRule201Response {
	return v.value
}

func (v *NullableCreateAlertRule201Response) Set(val *CreateAlertRule201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRule201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRule201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRule201Response(val *CreateAlertRule201Response) *NullableCreateAlertRule201Response {
	return &NullableCreateAlertRule201Response{value: val, isSet: true}
}

func (v NullableCreateAlertRule201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRule201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


