/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// StatusAlertRule The status of the alert rule. The supported status types are: - 1 (Enabled) - 2 (Disabled)
type StatusAlertRule int64

// List of statusAlertRule
const (
	STATUSALERTRULE__1 StatusAlertRule = 1
	STATUSALERTRULE__2 StatusAlertRule = 2
)

// All allowed values of StatusAlertRule enum
var AllowedStatusAlertRuleEnumValues = []StatusAlertRule{
	1,
	2,
}

func (v *StatusAlertRule) UnmarshalJSON(src []byte) error {
	var value int64
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StatusAlertRule(value)
	for _, existing := range AllowedStatusAlertRuleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StatusAlertRule", value)
}

// NewStatusAlertRuleFromValue returns a pointer to a valid StatusAlertRule
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatusAlertRuleFromValue(v int64) (*StatusAlertRule, error) {
	ev := StatusAlertRule(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StatusAlertRule: valid values are %v", v, AllowedStatusAlertRuleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StatusAlertRule) IsValid() bool {
	for _, existing := range AllowedStatusAlertRuleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to statusAlertRule value
func (v StatusAlertRule) Ptr() *StatusAlertRule {
	return &v
}

type NullableStatusAlertRule struct {
	value *StatusAlertRule
	isSet bool
}

func (v NullableStatusAlertRule) Get() *StatusAlertRule {
	return v.value
}

func (v *NullableStatusAlertRule) Set(val *StatusAlertRule) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusAlertRule) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusAlertRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusAlertRule(val *StatusAlertRule) *NullableStatusAlertRule {
	return &NullableStatusAlertRule{value: val, isSet: true}
}

func (v NullableStatusAlertRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusAlertRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

