/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TotalCountAlertsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotalCountAlertsResponse{}

// TotalCountAlertsResponse The total number of active alerts. Set `only_active_alerts_count=true` query parameter for the system to return the `total` field only.
type TotalCountAlertsResponse struct {
	// The total number of active alerts.
	Total int64 `json:"total"`
}

type _TotalCountAlertsResponse TotalCountAlertsResponse

// NewTotalCountAlertsResponse instantiates a new TotalCountAlertsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotalCountAlertsResponse(total int64) *TotalCountAlertsResponse {
	this := TotalCountAlertsResponse{}
	this.Total = total
	return &this
}

// NewTotalCountAlertsResponseWithDefaults instantiates a new TotalCountAlertsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotalCountAlertsResponseWithDefaults() *TotalCountAlertsResponse {
	this := TotalCountAlertsResponse{}
	return &this
}

// GetTotal returns the Total field value
func (o *TotalCountAlertsResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TotalCountAlertsResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TotalCountAlertsResponse) SetTotal(v int64) {
	o.Total = v
}

func (o TotalCountAlertsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotalCountAlertsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *TotalCountAlertsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTotalCountAlertsResponse := _TotalCountAlertsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTotalCountAlertsResponse)

	if err != nil {
		return err
	}

	*o = TotalCountAlertsResponse(varTotalCountAlertsResponse)

	return err
}

type NullableTotalCountAlertsResponse struct {
	value *TotalCountAlertsResponse
	isSet bool
}

func (v NullableTotalCountAlertsResponse) Get() *TotalCountAlertsResponse {
	return v.value
}

func (v *NullableTotalCountAlertsResponse) Set(val *TotalCountAlertsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTotalCountAlertsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTotalCountAlertsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotalCountAlertsResponse(val *TotalCountAlertsResponse) *NullableTotalCountAlertsResponse {
	return &NullableTotalCountAlertsResponse{value: val, isSet: true}
}

func (v NullableTotalCountAlertsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotalCountAlertsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


