/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
)

// checks if the UpdateAlertsStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertsStatus200Response{}

// UpdateAlertsStatus200Response The properties of the updated alert statuses.
type UpdateAlertsStatus200Response struct {
	// If all operations succeeded, the system returns `true`. If any ID is invalid, the system returns `false`.
	Success *bool `json:"success,omitempty"`
	// The list of IDs for the alert rules that the system updated.
	SuccessfulIds []string `json:"successfulIds,omitempty"`
	// The list of unique identifiers that either do no exist or the system failed to delete or update.
	ErrorIds []string `json:"errorIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAlertsStatus200Response UpdateAlertsStatus200Response

// NewUpdateAlertsStatus200Response instantiates a new UpdateAlertsStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertsStatus200Response() *UpdateAlertsStatus200Response {
	this := UpdateAlertsStatus200Response{}
	return &this
}

// NewUpdateAlertsStatus200ResponseWithDefaults instantiates a new UpdateAlertsStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertsStatus200ResponseWithDefaults() *UpdateAlertsStatus200Response {
	this := UpdateAlertsStatus200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateAlertsStatus200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertsStatus200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateAlertsStatus200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateAlertsStatus200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetSuccessfulIds returns the SuccessfulIds field value if set, zero value otherwise.
func (o *UpdateAlertsStatus200Response) GetSuccessfulIds() []string {
	if o == nil || IsNil(o.SuccessfulIds) {
		var ret []string
		return ret
	}
	return o.SuccessfulIds
}

// GetSuccessfulIdsOk returns a tuple with the SuccessfulIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertsStatus200Response) GetSuccessfulIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SuccessfulIds) {
		return nil, false
	}
	return o.SuccessfulIds, true
}

// HasSuccessfulIds returns a boolean if a field has been set.
func (o *UpdateAlertsStatus200Response) HasSuccessfulIds() bool {
	if o != nil && !IsNil(o.SuccessfulIds) {
		return true
	}

	return false
}

// SetSuccessfulIds gets a reference to the given []string and assigns it to the SuccessfulIds field.
func (o *UpdateAlertsStatus200Response) SetSuccessfulIds(v []string) {
	o.SuccessfulIds = v
}

// GetErrorIds returns the ErrorIds field value if set, zero value otherwise.
func (o *UpdateAlertsStatus200Response) GetErrorIds() []string {
	if o == nil || IsNil(o.ErrorIds) {
		var ret []string
		return ret
	}
	return o.ErrorIds
}

// GetErrorIdsOk returns a tuple with the ErrorIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAlertsStatus200Response) GetErrorIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ErrorIds) {
		return nil, false
	}
	return o.ErrorIds, true
}

// HasErrorIds returns a boolean if a field has been set.
func (o *UpdateAlertsStatus200Response) HasErrorIds() bool {
	if o != nil && !IsNil(o.ErrorIds) {
		return true
	}

	return false
}

// SetErrorIds gets a reference to the given []string and assigns it to the ErrorIds field.
func (o *UpdateAlertsStatus200Response) SetErrorIds(v []string) {
	o.ErrorIds = v
}

func (o UpdateAlertsStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertsStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.SuccessfulIds) {
		toSerialize["successfulIds"] = o.SuccessfulIds
	}
	if !IsNil(o.ErrorIds) {
		toSerialize["errorIds"] = o.ErrorIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAlertsStatus200Response) UnmarshalJSON(data []byte) (err error) {
	varUpdateAlertsStatus200Response := _UpdateAlertsStatus200Response{}

	err = json.Unmarshal(data, &varUpdateAlertsStatus200Response)

	if err != nil {
		return err
	}

	*o = UpdateAlertsStatus200Response(varUpdateAlertsStatus200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "successfulIds")
		delete(additionalProperties, "errorIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAlertsStatus200Response struct {
	value *UpdateAlertsStatus200Response
	isSet bool
}

func (v NullableUpdateAlertsStatus200Response) Get() *UpdateAlertsStatus200Response {
	return v.value
}

func (v *NullableUpdateAlertsStatus200Response) Set(val *UpdateAlertsStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertsStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertsStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertsStatus200Response(val *UpdateAlertsStatus200Response) *NullableUpdateAlertsStatus200Response {
	return &NullableUpdateAlertsStatus200Response{value: val, isSet: true}
}

func (v NullableUpdateAlertsStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertsStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


