/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// StatusAlert The status of the alert. The supported status types are: - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)
type StatusAlert int64

// List of statusAlert
const (
	STATUSALERT__1 StatusAlert = 1
	STATUSALERT__2 StatusAlert = 2
	STATUSALERT__3 StatusAlert = 3
	STATUSALERT__4 StatusAlert = 4
)

// All allowed values of StatusAlert enum
var AllowedStatusAlertEnumValues = []StatusAlert{
	1,
	2,
	3,
	4,
}

func (v *StatusAlert) UnmarshalJSON(src []byte) error {
	var value int64
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StatusAlert(value)
	for _, existing := range AllowedStatusAlertEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StatusAlert", value)
}

// NewStatusAlertFromValue returns a pointer to a valid StatusAlert
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStatusAlertFromValue(v int64) (*StatusAlert, error) {
	ev := StatusAlert(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StatusAlert: valid values are %v", v, AllowedStatusAlertEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StatusAlert) IsValid() bool {
	for _, existing := range AllowedStatusAlertEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to statusAlert value
func (v StatusAlert) Ptr() *StatusAlert {
	return &v
}

type NullableStatusAlert struct {
	value *StatusAlert
	isSet bool
}

func (v NullableStatusAlert) Get() *StatusAlert {
	return v.value
}

func (v *NullableStatusAlert) Set(val *StatusAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusAlert(val *StatusAlert) *NullableStatusAlert {
	return &NullableStatusAlert{value: val, isSet: true}
}

func (v NullableStatusAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

