/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateAlertRulesStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRulesStatusRequest{}

// UpdateAlertRulesStatusRequest The properties of the alert rules used by the system to update the alert rules.
type UpdateAlertRulesStatusRequest struct {
	// The numeric identifier of the status for the alert rule. Use `1` to enable the alert rule or `2` to disable the alert rule.
	Status int64 `json:"status"`
	// The list of identifiers used by the system to update the alert rules.
	EntityIds []int64 `json:"entity_ids"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAlertRulesStatusRequest UpdateAlertRulesStatusRequest

// NewUpdateAlertRulesStatusRequest instantiates a new UpdateAlertRulesStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertRulesStatusRequest(status int64, entityIds []int64) *UpdateAlertRulesStatusRequest {
	this := UpdateAlertRulesStatusRequest{}
	this.Status = status
	this.EntityIds = entityIds
	return &this
}

// NewUpdateAlertRulesStatusRequestWithDefaults instantiates a new UpdateAlertRulesStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertRulesStatusRequestWithDefaults() *UpdateAlertRulesStatusRequest {
	this := UpdateAlertRulesStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateAlertRulesStatusRequest) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertRulesStatusRequest) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateAlertRulesStatusRequest) SetStatus(v int64) {
	o.Status = v
}

// GetEntityIds returns the EntityIds field value
func (o *UpdateAlertRulesStatusRequest) GetEntityIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.EntityIds
}

// GetEntityIdsOk returns a tuple with the EntityIds field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertRulesStatusRequest) GetEntityIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.EntityIds, true
}

// SetEntityIds sets field value
func (o *UpdateAlertRulesStatusRequest) SetEntityIds(v []int64) {
	o.EntityIds = v
}

func (o UpdateAlertRulesStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertRulesStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["entity_ids"] = o.EntityIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAlertRulesStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"entity_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAlertRulesStatusRequest := _UpdateAlertRulesStatusRequest{}

	err = json.Unmarshal(data, &varUpdateAlertRulesStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateAlertRulesStatusRequest(varUpdateAlertRulesStatusRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "entity_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAlertRulesStatusRequest struct {
	value *UpdateAlertRulesStatusRequest
	isSet bool
}

func (v NullableUpdateAlertRulesStatusRequest) Get() *UpdateAlertRulesStatusRequest {
	return v.value
}

func (v *NullableUpdateAlertRulesStatusRequest) Set(val *UpdateAlertRulesStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertRulesStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertRulesStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertRulesStatusRequest(val *UpdateAlertRulesStatusRequest) *NullableUpdateAlertRulesStatusRequest {
	return &NullableUpdateAlertRulesStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateAlertRulesStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertRulesStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


