/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// SeverityAlert The severity of the alert. The supported severity levels are: - 1 (High) - 2 (Medium) - 3 (Low) - 4 (Info)
type SeverityAlert int64

// List of severityAlert
const (
	SEVERITYALERT__1 SeverityAlert = 1
	SEVERITYALERT__2 SeverityAlert = 2
	SEVERITYALERT__3 SeverityAlert = 3
	SEVERITYALERT__4 SeverityAlert = 4
)

// All allowed values of SeverityAlert enum
var AllowedSeverityAlertEnumValues = []SeverityAlert{
	1,
	2,
	3,
	4,
}

func (v *SeverityAlert) UnmarshalJSON(src []byte) error {
	var value int64
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SeverityAlert(value)
	for _, existing := range AllowedSeverityAlertEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SeverityAlert", value)
}

// NewSeverityAlertFromValue returns a pointer to a valid SeverityAlert
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSeverityAlertFromValue(v int64) (*SeverityAlert, error) {
	ev := SeverityAlert(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SeverityAlert: valid values are %v", v, AllowedSeverityAlertEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SeverityAlert) IsValid() bool {
	for _, existing := range AllowedSeverityAlertEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to severityAlert value
func (v SeverityAlert) Ptr() *SeverityAlert {
	return &v
}

type NullableSeverityAlert struct {
	value *SeverityAlert
	isSet bool
}

func (v NullableSeverityAlert) Get() *SeverityAlert {
	return v.value
}

func (v *NullableSeverityAlert) Set(val *SeverityAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableSeverityAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableSeverityAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeverityAlert(val *SeverityAlert) *NullableSeverityAlert {
	return &NullableSeverityAlert{value: val, isSet: true}
}

func (v NullableSeverityAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeverityAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

