/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// checks if the DeleteAlertRulesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteAlertRulesRequest{}

// DeleteAlertRulesRequest The properties of the alert rules used by the system to delete the alert rules.
type DeleteAlertRulesRequest struct {
	// The list of rule IDs used by the system to delete the alert rules.
	RuleIds []int64 `json:"ruleIds"`
	AdditionalProperties map[string]interface{}
}

type _DeleteAlertRulesRequest DeleteAlertRulesRequest

// NewDeleteAlertRulesRequest instantiates a new DeleteAlertRulesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAlertRulesRequest(ruleIds []int64) *DeleteAlertRulesRequest {
	this := DeleteAlertRulesRequest{}
	this.RuleIds = ruleIds
	return &this
}

// NewDeleteAlertRulesRequestWithDefaults instantiates a new DeleteAlertRulesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAlertRulesRequestWithDefaults() *DeleteAlertRulesRequest {
	this := DeleteAlertRulesRequest{}
	return &this
}

// GetRuleIds returns the RuleIds field value
func (o *DeleteAlertRulesRequest) GetRuleIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.RuleIds
}

// GetRuleIdsOk returns a tuple with the RuleIds field value
// and a boolean to check if the value has been set.
func (o *DeleteAlertRulesRequest) GetRuleIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleIds, true
}

// SetRuleIds sets field value
func (o *DeleteAlertRulesRequest) SetRuleIds(v []int64) {
	o.RuleIds = v
}

func (o DeleteAlertRulesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteAlertRulesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ruleIds"] = o.RuleIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeleteAlertRulesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ruleIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteAlertRulesRequest := _DeleteAlertRulesRequest{}

	err = json.Unmarshal(data, &varDeleteAlertRulesRequest)

	if err != nil {
		return err
	}

	*o = DeleteAlertRulesRequest(varDeleteAlertRulesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ruleIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteAlertRulesRequest struct {
	value *DeleteAlertRulesRequest
	isSet bool
}

func (v NullableDeleteAlertRulesRequest) Get() *DeleteAlertRulesRequest {
	return v.value
}

func (v *NullableDeleteAlertRulesRequest) Set(val *DeleteAlertRulesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAlertRulesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAlertRulesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAlertRulesRequest(val *DeleteAlertRulesRequest) *NullableDeleteAlertRulesRequest {
	return &NullableDeleteAlertRulesRequest{value: val, isSet: true}
}

func (v NullableDeleteAlertRulesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAlertRulesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


