/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"time"
)

// checks if the Alert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Alert{}

// Alert The properties of the alert.
type Alert struct {
	// The unique identifier of the alert.
	AlertId *string `json:"alertId,omitempty"`
	// The unique identifier of the organization.
	OrganizationId *int64 `json:"organization_id,omitempty"`
	// The description of the alert.
	Description *string `json:"description,omitempty"`
	Status *StatusAlert `json:"status,omitempty"`
	// The unique identifier of the associated rule.
	RuleId *int64 `json:"rule_id,omitempty"`
	// The time and date (ISO 8601 timestamp) when the system created the alert.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The time and date (ISO 8601 timestamp) when the system last modified the alert.
	ModifiedAt *time.Time `json:"modified_at,omitempty"`
	// The name of the alert.
	Name *string `json:"name,omitempty"`
	// The identifier of the rule type.  **Category: Connectivity**  | Rule Type ID | Rule Type Name | | --- | --- | | 1 | Network tunnel group disconnected | | 2 | No traffic through network tunnel group |  **Category: API Anomalies**  | Rule Type ID | Rule Type Name | | --- | --- | | 3 | Too many requests to get an access token | | 4 | High percentage of API errors | | 5 | Large number of rate limit errors | | 6 | More than one client using an API credential | | 7 | Authentication failures | | 8 | Programmatic creation of more than one API credential |  **Category: Data Usage**  | Rule Type ID | Rule Type Name | | --- | --- | | 9 | Data usage approaching limit |  **Category: Access Rule Changes**  | Rule Type ID | Rule Type Name | | --- | --- | | 10 | Rule creation, deletion, changing or reordering |  **Category: Behavior Analytics**  | Rule Type ID | Rule Type Name | | --- | --- | | 11 | Impossible travel detected | | 12 | Bulk upload operations | | 13 | Bulk download operations | | 14 | Bulk delete operations | | 15 | DLP violation spike | | 16 | Upload from high-risk countries | | 17 | Upload to high-risk countries |
	RuleTypeId *int64 `json:"rule_type_id,omitempty"`
	Severity *SeverityAlert `json:"severity,omitempty"`
	AccessRuleContext *AccessRuleContext `json:"access_rule_context,omitempty"`
	BehaviorAnalyticsContext *BehaviorAnalyticsContext `json:"behavior_analytics_context,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Alert Alert

// NewAlert instantiates a new Alert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlert() *Alert {
	this := Alert{}
	return &this
}

// NewAlertWithDefaults instantiates a new Alert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertWithDefaults() *Alert {
	this := Alert{}
	return &this
}

// GetAlertId returns the AlertId field value if set, zero value otherwise.
func (o *Alert) GetAlertId() string {
	if o == nil || IsNil(o.AlertId) {
		var ret string
		return ret
	}
	return *o.AlertId
}

// GetAlertIdOk returns a tuple with the AlertId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetAlertIdOk() (*string, bool) {
	if o == nil || IsNil(o.AlertId) {
		return nil, false
	}
	return o.AlertId, true
}

// HasAlertId returns a boolean if a field has been set.
func (o *Alert) HasAlertId() bool {
	if o != nil && !IsNil(o.AlertId) {
		return true
	}

	return false
}

// SetAlertId gets a reference to the given string and assigns it to the AlertId field.
func (o *Alert) SetAlertId(v string) {
	o.AlertId = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *Alert) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int64
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetOrganizationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *Alert) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int64 and assigns it to the OrganizationId field.
func (o *Alert) SetOrganizationId(v int64) {
	o.OrganizationId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Alert) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Alert) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Alert) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Alert) GetStatus() StatusAlert {
	if o == nil || IsNil(o.Status) {
		var ret StatusAlert
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetStatusOk() (*StatusAlert, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Alert) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given StatusAlert and assigns it to the Status field.
func (o *Alert) SetStatus(v StatusAlert) {
	o.Status = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *Alert) GetRuleId() int64 {
	if o == nil || IsNil(o.RuleId) {
		var ret int64
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetRuleIdOk() (*int64, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *Alert) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given int64 and assigns it to the RuleId field.
func (o *Alert) SetRuleId(v int64) {
	o.RuleId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Alert) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Alert) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Alert) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *Alert) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *Alert) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *Alert) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Alert) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Alert) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Alert) SetName(v string) {
	o.Name = &v
}

// GetRuleTypeId returns the RuleTypeId field value if set, zero value otherwise.
func (o *Alert) GetRuleTypeId() int64 {
	if o == nil || IsNil(o.RuleTypeId) {
		var ret int64
		return ret
	}
	return *o.RuleTypeId
}

// GetRuleTypeIdOk returns a tuple with the RuleTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetRuleTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.RuleTypeId) {
		return nil, false
	}
	return o.RuleTypeId, true
}

// HasRuleTypeId returns a boolean if a field has been set.
func (o *Alert) HasRuleTypeId() bool {
	if o != nil && !IsNil(o.RuleTypeId) {
		return true
	}

	return false
}

// SetRuleTypeId gets a reference to the given int64 and assigns it to the RuleTypeId field.
func (o *Alert) SetRuleTypeId(v int64) {
	o.RuleTypeId = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *Alert) GetSeverity() SeverityAlert {
	if o == nil || IsNil(o.Severity) {
		var ret SeverityAlert
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetSeverityOk() (*SeverityAlert, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *Alert) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given SeverityAlert and assigns it to the Severity field.
func (o *Alert) SetSeverity(v SeverityAlert) {
	o.Severity = &v
}

// GetAccessRuleContext returns the AccessRuleContext field value if set, zero value otherwise.
func (o *Alert) GetAccessRuleContext() AccessRuleContext {
	if o == nil || IsNil(o.AccessRuleContext) {
		var ret AccessRuleContext
		return ret
	}
	return *o.AccessRuleContext
}

// GetAccessRuleContextOk returns a tuple with the AccessRuleContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetAccessRuleContextOk() (*AccessRuleContext, bool) {
	if o == nil || IsNil(o.AccessRuleContext) {
		return nil, false
	}
	return o.AccessRuleContext, true
}

// HasAccessRuleContext returns a boolean if a field has been set.
func (o *Alert) HasAccessRuleContext() bool {
	if o != nil && !IsNil(o.AccessRuleContext) {
		return true
	}

	return false
}

// SetAccessRuleContext gets a reference to the given AccessRuleContext and assigns it to the AccessRuleContext field.
func (o *Alert) SetAccessRuleContext(v AccessRuleContext) {
	o.AccessRuleContext = &v
}

// GetBehaviorAnalyticsContext returns the BehaviorAnalyticsContext field value if set, zero value otherwise.
func (o *Alert) GetBehaviorAnalyticsContext() BehaviorAnalyticsContext {
	if o == nil || IsNil(o.BehaviorAnalyticsContext) {
		var ret BehaviorAnalyticsContext
		return ret
	}
	return *o.BehaviorAnalyticsContext
}

// GetBehaviorAnalyticsContextOk returns a tuple with the BehaviorAnalyticsContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Alert) GetBehaviorAnalyticsContextOk() (*BehaviorAnalyticsContext, bool) {
	if o == nil || IsNil(o.BehaviorAnalyticsContext) {
		return nil, false
	}
	return o.BehaviorAnalyticsContext, true
}

// HasBehaviorAnalyticsContext returns a boolean if a field has been set.
func (o *Alert) HasBehaviorAnalyticsContext() bool {
	if o != nil && !IsNil(o.BehaviorAnalyticsContext) {
		return true
	}

	return false
}

// SetBehaviorAnalyticsContext gets a reference to the given BehaviorAnalyticsContext and assigns it to the BehaviorAnalyticsContext field.
func (o *Alert) SetBehaviorAnalyticsContext(v BehaviorAnalyticsContext) {
	o.BehaviorAnalyticsContext = &v
}

func (o Alert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Alert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlertId) {
		toSerialize["alertId"] = o.AlertId
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RuleId) {
		toSerialize["rule_id"] = o.RuleId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modified_at"] = o.ModifiedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RuleTypeId) {
		toSerialize["rule_type_id"] = o.RuleTypeId
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.AccessRuleContext) {
		toSerialize["access_rule_context"] = o.AccessRuleContext
	}
	if !IsNil(o.BehaviorAnalyticsContext) {
		toSerialize["behavior_analytics_context"] = o.BehaviorAnalyticsContext
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Alert) UnmarshalJSON(data []byte) (err error) {
	varAlert := _Alert{}

	err = json.Unmarshal(data, &varAlert)

	if err != nil {
		return err
	}

	*o = Alert(varAlert)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alertId")
		delete(additionalProperties, "organization_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		delete(additionalProperties, "rule_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "modified_at")
		delete(additionalProperties, "name")
		delete(additionalProperties, "rule_type_id")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "access_rule_context")
		delete(additionalProperties, "behavior_analytics_context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAlert struct {
	value *Alert
	isSet bool
}

func (v NullableAlert) Get() *Alert {
	return v.value
}

func (v *NullableAlert) Set(val *Alert) {
	v.value = val
	v.isSet = true
}

func (v NullableAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlert(val *Alert) *NullableAlert {
	return &NullableAlert{value: val, isSet: true}
}

func (v NullableAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


