/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// NotificationTypeEmail The type of the notification.
type NotificationTypeEmail string

// List of notificationTypeEmail
const (
	NOTIFICATIONTYPEEMAIL_EMAIL NotificationTypeEmail = "email"
)

// All allowed values of NotificationTypeEmail enum
var AllowedNotificationTypeEmailEnumValues = []NotificationTypeEmail{
	"email",
}

func (v *NotificationTypeEmail) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationTypeEmail(value)
	for _, existing := range AllowedNotificationTypeEmailEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationTypeEmail", value)
}

// NewNotificationTypeEmailFromValue returns a pointer to a valid NotificationTypeEmail
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationTypeEmailFromValue(v string) (*NotificationTypeEmail, error) {
	ev := NotificationTypeEmail(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationTypeEmail: valid values are %v", v, AllowedNotificationTypeEmailEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationTypeEmail) IsValid() bool {
	for _, existing := range AllowedNotificationTypeEmailEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to notificationTypeEmail value
func (v NotificationTypeEmail) Ptr() *NotificationTypeEmail {
	return &v
}

type NullableNotificationTypeEmail struct {
	value *NotificationTypeEmail
	isSet bool
}

func (v NullableNotificationTypeEmail) Get() *NotificationTypeEmail {
	return v.value
}

func (v *NullableNotificationTypeEmail) Set(val *NotificationTypeEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationTypeEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationTypeEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationTypeEmail(val *NotificationTypeEmail) *NullableNotificationTypeEmail {
	return &NullableNotificationTypeEmail{value: val, isSet: true}
}

func (v NullableNotificationTypeEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationTypeEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

