/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
)

// checks if the ListAlertsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAlertsResponse{}

// ListAlertsResponse The properties of the alerts with the alert metadata.
type ListAlertsResponse struct {
	// The total number of active alerts.
	Total int64 `json:"total"`
	// The number of alerts categorized by the severity.
	SeverityCounts map[string]int64 `json:"severityCounts"`
	// The list of the details for the alerts.
	Alerts []AlertWithAdditionalContext `json:"alerts"`
	AdditionalProperties map[string]interface{}
}

type _ListAlertsResponse ListAlertsResponse

// NewListAlertsResponse instantiates a new ListAlertsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAlertsResponse(total int64, severityCounts map[string]int64, alerts []AlertWithAdditionalContext) *ListAlertsResponse {
	this := ListAlertsResponse{}
	this.Total = total
	this.SeverityCounts = severityCounts
	this.Alerts = alerts
	return &this
}

// NewListAlertsResponseWithDefaults instantiates a new ListAlertsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAlertsResponseWithDefaults() *ListAlertsResponse {
	this := ListAlertsResponse{}
	return &this
}

// GetTotal returns the Total field value
func (o *ListAlertsResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ListAlertsResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ListAlertsResponse) SetTotal(v int64) {
	o.Total = v
}

// GetSeverityCounts returns the SeverityCounts field value
func (o *ListAlertsResponse) GetSeverityCounts() map[string]int64 {
	if o == nil {
		var ret map[string]int64
		return ret
	}

	return o.SeverityCounts
}

// GetSeverityCountsOk returns a tuple with the SeverityCounts field value
// and a boolean to check if the value has been set.
func (o *ListAlertsResponse) GetSeverityCountsOk() (*map[string]int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeverityCounts, true
}

// SetSeverityCounts sets field value
func (o *ListAlertsResponse) SetSeverityCounts(v map[string]int64) {
	o.SeverityCounts = v
}

// GetAlerts returns the Alerts field value
func (o *ListAlertsResponse) GetAlerts() []AlertWithAdditionalContext {
	if o == nil {
		var ret []AlertWithAdditionalContext
		return ret
	}

	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value
// and a boolean to check if the value has been set.
func (o *ListAlertsResponse) GetAlertsOk() ([]AlertWithAdditionalContext, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alerts, true
}

// SetAlerts sets field value
func (o *ListAlertsResponse) SetAlerts(v []AlertWithAdditionalContext) {
	o.Alerts = v
}

func (o ListAlertsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAlertsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["severityCounts"] = o.SeverityCounts
	toSerialize["alerts"] = o.Alerts

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAlertsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"severityCounts",
		"alerts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAlertsResponse := _ListAlertsResponse{}

	err = json.Unmarshal(data, &varListAlertsResponse)

	if err != nil {
		return err
	}

	*o = ListAlertsResponse(varListAlertsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total")
		delete(additionalProperties, "severityCounts")
		delete(additionalProperties, "alerts")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAlertsResponse struct {
	value *ListAlertsResponse
	isSet bool
}

func (v NullableListAlertsResponse) Get() *ListAlertsResponse {
	return v.value
}

func (v *NullableListAlertsResponse) Set(val *ListAlertsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlertsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlertsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlertsResponse(val *ListAlertsResponse) *NullableListAlertsResponse {
	return &NullableListAlertsResponse{value: val, isSet: true}
}

func (v NullableListAlertsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlertsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


