/*
Cisco Secure Access Alerting API

Manage the alert rules in the organization and monitor the alerts generated by the alert rules.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alerting

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ListAlerts200Response - struct for ListAlerts200Response
type ListAlerts200Response struct {
	ListAlertsResponse *ListAlertsResponse
	TotalCountAlertsResponse *TotalCountAlertsResponse
}

// ListAlertsResponseAsListAlerts200Response is a convenience function that returns ListAlertsResponse wrapped in ListAlerts200Response
func ListAlertsResponseAsListAlerts200Response(v *ListAlertsResponse) ListAlerts200Response {
	return ListAlerts200Response{
		ListAlertsResponse: v,
	}
}

// TotalCountAlertsResponseAsListAlerts200Response is a convenience function that returns TotalCountAlertsResponse wrapped in ListAlerts200Response
func TotalCountAlertsResponseAsListAlerts200Response(v *TotalCountAlertsResponse) ListAlerts200Response {
	return ListAlerts200Response{
		TotalCountAlertsResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ListAlerts200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ListAlertsResponse
	err = newStrictDecoder(data).Decode(&dst.ListAlertsResponse)
	if err == nil {
		jsonListAlertsResponse, _ := json.Marshal(dst.ListAlertsResponse)
		if string(jsonListAlertsResponse) == "{}" { // empty struct
			dst.ListAlertsResponse = nil
		} else {
			if err = validator.Validate(dst.ListAlertsResponse); err != nil {
				dst.ListAlertsResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.ListAlertsResponse = nil
	}

	// try to unmarshal data into TotalCountAlertsResponse
	err = newStrictDecoder(data).Decode(&dst.TotalCountAlertsResponse)
	if err == nil {
		jsonTotalCountAlertsResponse, _ := json.Marshal(dst.TotalCountAlertsResponse)
		if string(jsonTotalCountAlertsResponse) == "{}" { // empty struct
			dst.TotalCountAlertsResponse = nil
		} else {
			if err = validator.Validate(dst.TotalCountAlertsResponse); err != nil {
				dst.TotalCountAlertsResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.TotalCountAlertsResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ListAlertsResponse = nil
		dst.TotalCountAlertsResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ListAlerts200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ListAlerts200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ListAlerts200Response) MarshalJSON() ([]byte, error) {
	if src.ListAlertsResponse != nil {
		return json.Marshal(&src.ListAlertsResponse)
	}

	if src.TotalCountAlertsResponse != nil {
		return json.Marshal(&src.TotalCountAlertsResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ListAlerts200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ListAlertsResponse != nil {
		return obj.ListAlertsResponse
	}

	if obj.TotalCountAlertsResponse != nil {
		return obj.TotalCountAlertsResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ListAlerts200Response) GetActualInstanceValue() (interface{}) {
	if obj.ListAlertsResponse != nil {
		return *obj.ListAlertsResponse
	}

	if obj.TotalCountAlertsResponse != nil {
		return *obj.TotalCountAlertsResponse
	}

	// all schemas are nil
	return nil
}

type NullableListAlerts200Response struct {
	value *ListAlerts200Response
	isSet bool
}

func (v NullableListAlerts200Response) Get() *ListAlerts200Response {
	return v.value
}

func (v *NullableListAlerts200Response) Set(val *ListAlerts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAlerts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAlerts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAlerts200Response(val *ListAlerts200Response) *NullableListAlerts200Response {
	return &NullableListAlerts200Response{value: val, isSet: true}
}

func (v NullableListAlerts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAlerts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


