/*
Cisco Secure Access Virtual Appliances API

Manage the Virtual Appliances (VAs) in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package virtualappliances

import (
	"encoding/json"
)

// checks if the VirtualApplianceObjectState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VirtualApplianceObjectState{}

// VirtualApplianceObjectState The properties for the state of the virtual appliance.
type VirtualApplianceObjectState struct {
	// The virtual appliance that is connected to the connector status.
	ConnectedToConnector *string `json:"connectedToConnector,omitempty"`
	// The virtual appliance has local domain configuration.
	HasLocalDomainConfigured *string `json:"hasLocalDomainConfigured,omitempty"`
	// The failure rate of the query for the virtual appliance is acceptable.
	QueryFailureRateAcceptable *string `json:"queryFailureRateAcceptable,omitempty"`
	// The virtual appliance received internal DNS queries.
	ReceivedInternalDNSQueries *string `json:"receivedInternalDNSQueries,omitempty"`
	// The virtual appliance is redundant within site.
	RedundantWithinSite *string `json:"redundantWithinSite,omitempty"`
	// The virtual appliance is syncing.
	Syncing *string `json:"syncing,omitempty"`
}

// NewVirtualApplianceObjectState instantiates a new VirtualApplianceObjectState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualApplianceObjectState() *VirtualApplianceObjectState {
	this := VirtualApplianceObjectState{}
	return &this
}

// NewVirtualApplianceObjectStateWithDefaults instantiates a new VirtualApplianceObjectState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualApplianceObjectStateWithDefaults() *VirtualApplianceObjectState {
	this := VirtualApplianceObjectState{}
	return &this
}

// GetConnectedToConnector returns the ConnectedToConnector field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetConnectedToConnector() string {
	if o == nil || IsNil(o.ConnectedToConnector) {
		var ret string
		return ret
	}
	return *o.ConnectedToConnector
}

// GetConnectedToConnectorOk returns a tuple with the ConnectedToConnector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetConnectedToConnectorOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectedToConnector) {
		return nil, false
	}
	return o.ConnectedToConnector, true
}

// HasConnectedToConnector returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasConnectedToConnector() bool {
	if o != nil && !IsNil(o.ConnectedToConnector) {
		return true
	}

	return false
}

// SetConnectedToConnector gets a reference to the given string and assigns it to the ConnectedToConnector field.
func (o *VirtualApplianceObjectState) SetConnectedToConnector(v string) {
	o.ConnectedToConnector = &v
}

// GetHasLocalDomainConfigured returns the HasLocalDomainConfigured field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetHasLocalDomainConfigured() string {
	if o == nil || IsNil(o.HasLocalDomainConfigured) {
		var ret string
		return ret
	}
	return *o.HasLocalDomainConfigured
}

// GetHasLocalDomainConfiguredOk returns a tuple with the HasLocalDomainConfigured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetHasLocalDomainConfiguredOk() (*string, bool) {
	if o == nil || IsNil(o.HasLocalDomainConfigured) {
		return nil, false
	}
	return o.HasLocalDomainConfigured, true
}

// HasHasLocalDomainConfigured returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasHasLocalDomainConfigured() bool {
	if o != nil && !IsNil(o.HasLocalDomainConfigured) {
		return true
	}

	return false
}

// SetHasLocalDomainConfigured gets a reference to the given string and assigns it to the HasLocalDomainConfigured field.
func (o *VirtualApplianceObjectState) SetHasLocalDomainConfigured(v string) {
	o.HasLocalDomainConfigured = &v
}

// GetQueryFailureRateAcceptable returns the QueryFailureRateAcceptable field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetQueryFailureRateAcceptable() string {
	if o == nil || IsNil(o.QueryFailureRateAcceptable) {
		var ret string
		return ret
	}
	return *o.QueryFailureRateAcceptable
}

// GetQueryFailureRateAcceptableOk returns a tuple with the QueryFailureRateAcceptable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetQueryFailureRateAcceptableOk() (*string, bool) {
	if o == nil || IsNil(o.QueryFailureRateAcceptable) {
		return nil, false
	}
	return o.QueryFailureRateAcceptable, true
}

// HasQueryFailureRateAcceptable returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasQueryFailureRateAcceptable() bool {
	if o != nil && !IsNil(o.QueryFailureRateAcceptable) {
		return true
	}

	return false
}

// SetQueryFailureRateAcceptable gets a reference to the given string and assigns it to the QueryFailureRateAcceptable field.
func (o *VirtualApplianceObjectState) SetQueryFailureRateAcceptable(v string) {
	o.QueryFailureRateAcceptable = &v
}

// GetReceivedInternalDNSQueries returns the ReceivedInternalDNSQueries field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetReceivedInternalDNSQueries() string {
	if o == nil || IsNil(o.ReceivedInternalDNSQueries) {
		var ret string
		return ret
	}
	return *o.ReceivedInternalDNSQueries
}

// GetReceivedInternalDNSQueriesOk returns a tuple with the ReceivedInternalDNSQueries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetReceivedInternalDNSQueriesOk() (*string, bool) {
	if o == nil || IsNil(o.ReceivedInternalDNSQueries) {
		return nil, false
	}
	return o.ReceivedInternalDNSQueries, true
}

// HasReceivedInternalDNSQueries returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasReceivedInternalDNSQueries() bool {
	if o != nil && !IsNil(o.ReceivedInternalDNSQueries) {
		return true
	}

	return false
}

// SetReceivedInternalDNSQueries gets a reference to the given string and assigns it to the ReceivedInternalDNSQueries field.
func (o *VirtualApplianceObjectState) SetReceivedInternalDNSQueries(v string) {
	o.ReceivedInternalDNSQueries = &v
}

// GetRedundantWithinSite returns the RedundantWithinSite field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetRedundantWithinSite() string {
	if o == nil || IsNil(o.RedundantWithinSite) {
		var ret string
		return ret
	}
	return *o.RedundantWithinSite
}

// GetRedundantWithinSiteOk returns a tuple with the RedundantWithinSite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetRedundantWithinSiteOk() (*string, bool) {
	if o == nil || IsNil(o.RedundantWithinSite) {
		return nil, false
	}
	return o.RedundantWithinSite, true
}

// HasRedundantWithinSite returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasRedundantWithinSite() bool {
	if o != nil && !IsNil(o.RedundantWithinSite) {
		return true
	}

	return false
}

// SetRedundantWithinSite gets a reference to the given string and assigns it to the RedundantWithinSite field.
func (o *VirtualApplianceObjectState) SetRedundantWithinSite(v string) {
	o.RedundantWithinSite = &v
}

// GetSyncing returns the Syncing field value if set, zero value otherwise.
func (o *VirtualApplianceObjectState) GetSyncing() string {
	if o == nil || IsNil(o.Syncing) {
		var ret string
		return ret
	}
	return *o.Syncing
}

// GetSyncingOk returns a tuple with the Syncing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectState) GetSyncingOk() (*string, bool) {
	if o == nil || IsNil(o.Syncing) {
		return nil, false
	}
	return o.Syncing, true
}

// HasSyncing returns a boolean if a field has been set.
func (o *VirtualApplianceObjectState) HasSyncing() bool {
	if o != nil && !IsNil(o.Syncing) {
		return true
	}

	return false
}

// SetSyncing gets a reference to the given string and assigns it to the Syncing field.
func (o *VirtualApplianceObjectState) SetSyncing(v string) {
	o.Syncing = &v
}

func (o VirtualApplianceObjectState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VirtualApplianceObjectState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConnectedToConnector) {
		toSerialize["connectedToConnector"] = o.ConnectedToConnector
	}
	if !IsNil(o.HasLocalDomainConfigured) {
		toSerialize["hasLocalDomainConfigured"] = o.HasLocalDomainConfigured
	}
	if !IsNil(o.QueryFailureRateAcceptable) {
		toSerialize["queryFailureRateAcceptable"] = o.QueryFailureRateAcceptable
	}
	if !IsNil(o.ReceivedInternalDNSQueries) {
		toSerialize["receivedInternalDNSQueries"] = o.ReceivedInternalDNSQueries
	}
	if !IsNil(o.RedundantWithinSite) {
		toSerialize["redundantWithinSite"] = o.RedundantWithinSite
	}
	if !IsNil(o.Syncing) {
		toSerialize["syncing"] = o.Syncing
	}
	return toSerialize, nil
}

type NullableVirtualApplianceObjectState struct {
	value *VirtualApplianceObjectState
	isSet bool
}

func (v NullableVirtualApplianceObjectState) Get() *VirtualApplianceObjectState {
	return v.value
}

func (v *NullableVirtualApplianceObjectState) Set(val *VirtualApplianceObjectState) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualApplianceObjectState) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualApplianceObjectState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualApplianceObjectState(val *VirtualApplianceObjectState) *NullableVirtualApplianceObjectState {
	return &NullableVirtualApplianceObjectState{value: val, isSet: true}
}

func (v NullableVirtualApplianceObjectState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualApplianceObjectState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


