/*
Cisco Secure Access Virtual Appliances API

Manage the Virtual Appliances (VAs) in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package virtualappliances

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the VirtualApplianceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VirtualApplianceObject{}

// VirtualApplianceObject The properties of the virtual appliance.
type VirtualApplianceObject struct {
	// The origin ID of the virtual appliance.
	OriginId int64 `json:"originId"`
	// The name of the virtual appliance.
	Name string `json:"name"`
	// The site ID of the virtual appliance.
	SiteId *int64 `json:"siteId,omitempty"`
	// Specifies whether you can upgrade the virtual appliance (VA) to the latest VA version.
	IsUpgradable bool `json:"isUpgradable"`
	State *VirtualApplianceObjectState `json:"state,omitempty"`
	// A description of the health of the virtual appliance.
	Health string `json:"health"`
	// The type of the virtual appliance.
	Type string `json:"type"`
	Settings *VirtualApplianceObjectSettings `json:"settings,omitempty"`
	// The date and time (ISO8601 timestamp) when the VA was created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The date and time (ISO8601 timestamp) when the VA was modified.
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	// The date and time (ISO8601 timestamp) when the virtual appliance's state was updated.
	StateUpdatedAt time.Time `json:"stateUpdatedAt"`
	AdditionalProperties map[string]interface{}
}

type _VirtualApplianceObject VirtualApplianceObject

// NewVirtualApplianceObject instantiates a new VirtualApplianceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualApplianceObject(originId int64, name string, isUpgradable bool, health string, type_ string, stateUpdatedAt time.Time) *VirtualApplianceObject {
	this := VirtualApplianceObject{}
	this.OriginId = originId
	this.Name = name
	this.IsUpgradable = isUpgradable
	this.Health = health
	this.Type = type_
	this.StateUpdatedAt = stateUpdatedAt
	return &this
}

// NewVirtualApplianceObjectWithDefaults instantiates a new VirtualApplianceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualApplianceObjectWithDefaults() *VirtualApplianceObject {
	this := VirtualApplianceObject{}
	return &this
}

// GetOriginId returns the OriginId field value
func (o *VirtualApplianceObject) GetOriginId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OriginId
}

// GetOriginIdOk returns a tuple with the OriginId field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetOriginIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginId, true
}

// SetOriginId sets field value
func (o *VirtualApplianceObject) SetOriginId(v int64) {
	o.OriginId = v
}

// GetName returns the Name field value
func (o *VirtualApplianceObject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VirtualApplianceObject) SetName(v string) {
	o.Name = v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *VirtualApplianceObject) GetSiteId() int64 {
	if o == nil || IsNil(o.SiteId) {
		var ret int64
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetSiteIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *VirtualApplianceObject) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given int64 and assigns it to the SiteId field.
func (o *VirtualApplianceObject) SetSiteId(v int64) {
	o.SiteId = &v
}

// GetIsUpgradable returns the IsUpgradable field value
func (o *VirtualApplianceObject) GetIsUpgradable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsUpgradable
}

// GetIsUpgradableOk returns a tuple with the IsUpgradable field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetIsUpgradableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsUpgradable, true
}

// SetIsUpgradable sets field value
func (o *VirtualApplianceObject) SetIsUpgradable(v bool) {
	o.IsUpgradable = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *VirtualApplianceObject) GetState() VirtualApplianceObjectState {
	if o == nil || IsNil(o.State) {
		var ret VirtualApplianceObjectState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetStateOk() (*VirtualApplianceObjectState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *VirtualApplianceObject) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given VirtualApplianceObjectState and assigns it to the State field.
func (o *VirtualApplianceObject) SetState(v VirtualApplianceObjectState) {
	o.State = &v
}

// GetHealth returns the Health field value
func (o *VirtualApplianceObject) GetHealth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Health
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetHealthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Health, true
}

// SetHealth sets field value
func (o *VirtualApplianceObject) SetHealth(v string) {
	o.Health = v
}

// GetType returns the Type field value
func (o *VirtualApplianceObject) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VirtualApplianceObject) SetType(v string) {
	o.Type = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *VirtualApplianceObject) GetSettings() VirtualApplianceObjectSettings {
	if o == nil || IsNil(o.Settings) {
		var ret VirtualApplianceObjectSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetSettingsOk() (*VirtualApplianceObjectSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *VirtualApplianceObject) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given VirtualApplianceObjectSettings and assigns it to the Settings field.
func (o *VirtualApplianceObject) SetSettings(v VirtualApplianceObjectSettings) {
	o.Settings = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *VirtualApplianceObject) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *VirtualApplianceObject) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *VirtualApplianceObject) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetModifiedAt returns the ModifiedAt field value if set, zero value otherwise.
func (o *VirtualApplianceObject) GetModifiedAt() time.Time {
	if o == nil || IsNil(o.ModifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetModifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedAt) {
		return nil, false
	}
	return o.ModifiedAt, true
}

// HasModifiedAt returns a boolean if a field has been set.
func (o *VirtualApplianceObject) HasModifiedAt() bool {
	if o != nil && !IsNil(o.ModifiedAt) {
		return true
	}

	return false
}

// SetModifiedAt gets a reference to the given time.Time and assigns it to the ModifiedAt field.
func (o *VirtualApplianceObject) SetModifiedAt(v time.Time) {
	o.ModifiedAt = &v
}

// GetStateUpdatedAt returns the StateUpdatedAt field value
func (o *VirtualApplianceObject) GetStateUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StateUpdatedAt
}

// GetStateUpdatedAtOk returns a tuple with the StateUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObject) GetStateUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateUpdatedAt, true
}

// SetStateUpdatedAt sets field value
func (o *VirtualApplianceObject) SetStateUpdatedAt(v time.Time) {
	o.StateUpdatedAt = v
}

func (o VirtualApplianceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VirtualApplianceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["originId"] = o.OriginId
	toSerialize["name"] = o.Name
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	toSerialize["isUpgradable"] = o.IsUpgradable
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["health"] = o.Health
	toSerialize["type"] = o.Type
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.ModifiedAt) {
		toSerialize["modifiedAt"] = o.ModifiedAt
	}
	toSerialize["stateUpdatedAt"] = o.StateUpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VirtualApplianceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"originId",
		"name",
		"isUpgradable",
		"health",
		"type",
		"stateUpdatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVirtualApplianceObject := _VirtualApplianceObject{}

	err = json.Unmarshal(data, &varVirtualApplianceObject)

	if err != nil {
		return err
	}

	*o = VirtualApplianceObject(varVirtualApplianceObject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "originId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "siteId")
		delete(additionalProperties, "isUpgradable")
		delete(additionalProperties, "state")
		delete(additionalProperties, "health")
		delete(additionalProperties, "type")
		delete(additionalProperties, "settings")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		delete(additionalProperties, "stateUpdatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVirtualApplianceObject struct {
	value *VirtualApplianceObject
	isSet bool
}

func (v NullableVirtualApplianceObject) Get() *VirtualApplianceObject {
	return v.value
}

func (v *NullableVirtualApplianceObject) Set(val *VirtualApplianceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualApplianceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualApplianceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualApplianceObject(val *VirtualApplianceObject) *NullableVirtualApplianceObject {
	return &NullableVirtualApplianceObject{value: val, isSet: true}
}

func (v NullableVirtualApplianceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualApplianceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


