/*
Cisco Secure Access Virtual Appliances API

Manage the Virtual Appliances (VAs) in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package virtualappliances

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateVirtualApplianceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVirtualApplianceRequest{}

// UpdateVirtualApplianceRequest struct for UpdateVirtualApplianceRequest
type UpdateVirtualApplianceRequest struct {
	// The ID of the site.
	SiteId int64 `json:"siteId"`
	AdditionalProperties map[string]interface{}
}

type _UpdateVirtualApplianceRequest UpdateVirtualApplianceRequest

// NewUpdateVirtualApplianceRequest instantiates a new UpdateVirtualApplianceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateVirtualApplianceRequest(siteId int64) *UpdateVirtualApplianceRequest {
	this := UpdateVirtualApplianceRequest{}
	this.SiteId = siteId
	return &this
}

// NewUpdateVirtualApplianceRequestWithDefaults instantiates a new UpdateVirtualApplianceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateVirtualApplianceRequestWithDefaults() *UpdateVirtualApplianceRequest {
	this := UpdateVirtualApplianceRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *UpdateVirtualApplianceRequest) GetSiteId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *UpdateVirtualApplianceRequest) GetSiteIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *UpdateVirtualApplianceRequest) SetSiteId(v int64) {
	o.SiteId = v
}

func (o UpdateVirtualApplianceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVirtualApplianceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateVirtualApplianceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateVirtualApplianceRequest := _UpdateVirtualApplianceRequest{}

	err = json.Unmarshal(data, &varUpdateVirtualApplianceRequest)

	if err != nil {
		return err
	}

	*o = UpdateVirtualApplianceRequest(varUpdateVirtualApplianceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "siteId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateVirtualApplianceRequest struct {
	value *UpdateVirtualApplianceRequest
	isSet bool
}

func (v NullableUpdateVirtualApplianceRequest) Get() *UpdateVirtualApplianceRequest {
	return v.value
}

func (v *NullableUpdateVirtualApplianceRequest) Set(val *UpdateVirtualApplianceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVirtualApplianceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVirtualApplianceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVirtualApplianceRequest(val *UpdateVirtualApplianceRequest) *NullableUpdateVirtualApplianceRequest {
	return &NullableUpdateVirtualApplianceRequest{value: val, isSet: true}
}

func (v NullableUpdateVirtualApplianceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVirtualApplianceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


