/*
Cisco Secure Access Virtual Appliances API

Manage the Virtual Appliances (VAs) in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package virtualappliances

import (
	"encoding/json"
)

// checks if the ListVirtualAppliances404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVirtualAppliances404Response{}

// ListVirtualAppliances404Response struct for ListVirtualAppliances404Response
type ListVirtualAppliances404Response struct {
	// HTTP status code
	StatusCode *int64 `json:"statusCode,omitempty"`
	// A brief description of the error
	Error *string `json:"error,omitempty"`
	// Detailed error message
	Message *string `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListVirtualAppliances404Response ListVirtualAppliances404Response

// NewListVirtualAppliances404Response instantiates a new ListVirtualAppliances404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVirtualAppliances404Response() *ListVirtualAppliances404Response {
	this := ListVirtualAppliances404Response{}
	return &this
}

// NewListVirtualAppliances404ResponseWithDefaults instantiates a new ListVirtualAppliances404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVirtualAppliances404ResponseWithDefaults() *ListVirtualAppliances404Response {
	this := ListVirtualAppliances404Response{}
	return &this
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ListVirtualAppliances404Response) GetStatusCode() int64 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int64
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVirtualAppliances404Response) GetStatusCodeOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ListVirtualAppliances404Response) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int64 and assigns it to the StatusCode field.
func (o *ListVirtualAppliances404Response) SetStatusCode(v int64) {
	o.StatusCode = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ListVirtualAppliances404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVirtualAppliances404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ListVirtualAppliances404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ListVirtualAppliances404Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ListVirtualAppliances404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVirtualAppliances404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ListVirtualAppliances404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ListVirtualAppliances404Response) SetMessage(v string) {
	o.Message = &v
}

func (o ListVirtualAppliances404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVirtualAppliances404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListVirtualAppliances404Response) UnmarshalJSON(data []byte) (err error) {
	varListVirtualAppliances404Response := _ListVirtualAppliances404Response{}

	err = json.Unmarshal(data, &varListVirtualAppliances404Response)

	if err != nil {
		return err
	}

	*o = ListVirtualAppliances404Response(varListVirtualAppliances404Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "statusCode")
		delete(additionalProperties, "error")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListVirtualAppliances404Response struct {
	value *ListVirtualAppliances404Response
	isSet bool
}

func (v NullableListVirtualAppliances404Response) Get() *ListVirtualAppliances404Response {
	return v.value
}

func (v *NullableListVirtualAppliances404Response) Set(val *ListVirtualAppliances404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListVirtualAppliances404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListVirtualAppliances404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVirtualAppliances404Response(val *ListVirtualAppliances404Response) *NullableListVirtualAppliances404Response {
	return &NullableListVirtualAppliances404Response{value: val, isSet: true}
}

func (v NullableListVirtualAppliances404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVirtualAppliances404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


