/*
Cisco Secure Access Virtual Appliances API

Manage the Virtual Appliances (VAs) in your organization.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package virtualappliances

import (
	"encoding/json"
	"time"
)

// checks if the VirtualApplianceObjectSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VirtualApplianceObjectSettings{}

// VirtualApplianceObjectSettings The properties of the settings on the virtual appliance.
type VirtualApplianceObjectSettings struct {
	// A list of internal IP addresses.
	InternalIPs []string `json:"internalIPs,omitempty"`
	// The external IP address.
	ExternalIP *string `json:"externalIP,omitempty"`
	// The type of the host.
	HostType *string `json:"hostType,omitempty"`
	// The uptime in seconds.
	Uptime *int64 `json:"uptime,omitempty"`
	// Specifies whether DNSCrypt is enabled.
	IsDnscryptEnabled *bool `json:"isDnscryptEnabled,omitempty"`
	// Specifies the version of the virtual appliance.
	Version *string `json:"version,omitempty"`
	// Specifies the upgrade error.
	UpgradeError *string `json:"upgradeError,omitempty"`
	// The list of domains.
	Domains []string `json:"domains,omitempty"`
	// The date and time (ISO8601 timestamp) of the last sync.
	LastSyncTime *time.Time `json:"lastSyncTime,omitempty"`
}

// NewVirtualApplianceObjectSettings instantiates a new VirtualApplianceObjectSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualApplianceObjectSettings() *VirtualApplianceObjectSettings {
	this := VirtualApplianceObjectSettings{}
	return &this
}

// NewVirtualApplianceObjectSettingsWithDefaults instantiates a new VirtualApplianceObjectSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualApplianceObjectSettingsWithDefaults() *VirtualApplianceObjectSettings {
	this := VirtualApplianceObjectSettings{}
	return &this
}

// GetInternalIPs returns the InternalIPs field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetInternalIPs() []string {
	if o == nil || IsNil(o.InternalIPs) {
		var ret []string
		return ret
	}
	return o.InternalIPs
}

// GetInternalIPsOk returns a tuple with the InternalIPs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetInternalIPsOk() ([]string, bool) {
	if o == nil || IsNil(o.InternalIPs) {
		return nil, false
	}
	return o.InternalIPs, true
}

// HasInternalIPs returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasInternalIPs() bool {
	if o != nil && !IsNil(o.InternalIPs) {
		return true
	}

	return false
}

// SetInternalIPs gets a reference to the given []string and assigns it to the InternalIPs field.
func (o *VirtualApplianceObjectSettings) SetInternalIPs(v []string) {
	o.InternalIPs = v
}

// GetExternalIP returns the ExternalIP field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetExternalIP() string {
	if o == nil || IsNil(o.ExternalIP) {
		var ret string
		return ret
	}
	return *o.ExternalIP
}

// GetExternalIPOk returns a tuple with the ExternalIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetExternalIPOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalIP) {
		return nil, false
	}
	return o.ExternalIP, true
}

// HasExternalIP returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasExternalIP() bool {
	if o != nil && !IsNil(o.ExternalIP) {
		return true
	}

	return false
}

// SetExternalIP gets a reference to the given string and assigns it to the ExternalIP field.
func (o *VirtualApplianceObjectSettings) SetExternalIP(v string) {
	o.ExternalIP = &v
}

// GetHostType returns the HostType field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetHostType() string {
	if o == nil || IsNil(o.HostType) {
		var ret string
		return ret
	}
	return *o.HostType
}

// GetHostTypeOk returns a tuple with the HostType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetHostTypeOk() (*string, bool) {
	if o == nil || IsNil(o.HostType) {
		return nil, false
	}
	return o.HostType, true
}

// HasHostType returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasHostType() bool {
	if o != nil && !IsNil(o.HostType) {
		return true
	}

	return false
}

// SetHostType gets a reference to the given string and assigns it to the HostType field.
func (o *VirtualApplianceObjectSettings) SetHostType(v string) {
	o.HostType = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetUptime() int64 {
	if o == nil || IsNil(o.Uptime) {
		var ret int64
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetUptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int64 and assigns it to the Uptime field.
func (o *VirtualApplianceObjectSettings) SetUptime(v int64) {
	o.Uptime = &v
}

// GetIsDnscryptEnabled returns the IsDnscryptEnabled field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetIsDnscryptEnabled() bool {
	if o == nil || IsNil(o.IsDnscryptEnabled) {
		var ret bool
		return ret
	}
	return *o.IsDnscryptEnabled
}

// GetIsDnscryptEnabledOk returns a tuple with the IsDnscryptEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetIsDnscryptEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDnscryptEnabled) {
		return nil, false
	}
	return o.IsDnscryptEnabled, true
}

// HasIsDnscryptEnabled returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasIsDnscryptEnabled() bool {
	if o != nil && !IsNil(o.IsDnscryptEnabled) {
		return true
	}

	return false
}

// SetIsDnscryptEnabled gets a reference to the given bool and assigns it to the IsDnscryptEnabled field.
func (o *VirtualApplianceObjectSettings) SetIsDnscryptEnabled(v bool) {
	o.IsDnscryptEnabled = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *VirtualApplianceObjectSettings) SetVersion(v string) {
	o.Version = &v
}

// GetUpgradeError returns the UpgradeError field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetUpgradeError() string {
	if o == nil || IsNil(o.UpgradeError) {
		var ret string
		return ret
	}
	return *o.UpgradeError
}

// GetUpgradeErrorOk returns a tuple with the UpgradeError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetUpgradeErrorOk() (*string, bool) {
	if o == nil || IsNil(o.UpgradeError) {
		return nil, false
	}
	return o.UpgradeError, true
}

// HasUpgradeError returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasUpgradeError() bool {
	if o != nil && !IsNil(o.UpgradeError) {
		return true
	}

	return false
}

// SetUpgradeError gets a reference to the given string and assigns it to the UpgradeError field.
func (o *VirtualApplianceObjectSettings) SetUpgradeError(v string) {
	o.UpgradeError = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetDomains() []string {
	if o == nil || IsNil(o.Domains) {
		var ret []string
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *VirtualApplianceObjectSettings) SetDomains(v []string) {
	o.Domains = v
}

// GetLastSyncTime returns the LastSyncTime field value if set, zero value otherwise.
func (o *VirtualApplianceObjectSettings) GetLastSyncTime() time.Time {
	if o == nil || IsNil(o.LastSyncTime) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncTime
}

// GetLastSyncTimeOk returns a tuple with the LastSyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualApplianceObjectSettings) GetLastSyncTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncTime) {
		return nil, false
	}
	return o.LastSyncTime, true
}

// HasLastSyncTime returns a boolean if a field has been set.
func (o *VirtualApplianceObjectSettings) HasLastSyncTime() bool {
	if o != nil && !IsNil(o.LastSyncTime) {
		return true
	}

	return false
}

// SetLastSyncTime gets a reference to the given time.Time and assigns it to the LastSyncTime field.
func (o *VirtualApplianceObjectSettings) SetLastSyncTime(v time.Time) {
	o.LastSyncTime = &v
}

func (o VirtualApplianceObjectSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VirtualApplianceObjectSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InternalIPs) {
		toSerialize["internalIPs"] = o.InternalIPs
	}
	if !IsNil(o.ExternalIP) {
		toSerialize["externalIP"] = o.ExternalIP
	}
	if !IsNil(o.HostType) {
		toSerialize["hostType"] = o.HostType
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.IsDnscryptEnabled) {
		toSerialize["isDnscryptEnabled"] = o.IsDnscryptEnabled
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.UpgradeError) {
		toSerialize["upgradeError"] = o.UpgradeError
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.LastSyncTime) {
		toSerialize["lastSyncTime"] = o.LastSyncTime
	}
	return toSerialize, nil
}

type NullableVirtualApplianceObjectSettings struct {
	value *VirtualApplianceObjectSettings
	isSet bool
}

func (v NullableVirtualApplianceObjectSettings) Get() *VirtualApplianceObjectSettings {
	return v.value
}

func (v *NullableVirtualApplianceObjectSettings) Set(val *VirtualApplianceObjectSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualApplianceObjectSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualApplianceObjectSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualApplianceObjectSettings(val *VirtualApplianceObjectSettings) *NullableVirtualApplianceObjectSettings {
	return &NullableVirtualApplianceObjectSettings{value: val, isSet: true}
}

func (v NullableVirtualApplianceObjectSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualApplianceObjectSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


