/*
Cisco Secure Access Virtual Appliances API

Testing VirtualAppliancesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package virtualappliances

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CiscoDevNet/go-ciscosecureaccess/virtualappliances"
)

func Test_virtualappliances_VirtualAppliancesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VirtualAppliancesAPIService DeleteVirtualAppliance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var virtualApplianceId int64

		httpRes, err := apiClient.VirtualAppliancesAPI.DeleteVirtualAppliance(context.Background(), virtualApplianceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VirtualAppliancesAPIService GetVirtualAppliance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var virtualApplianceId int64

		resp, httpRes, err := apiClient.VirtualAppliancesAPI.GetVirtualAppliance(context.Background(), virtualApplianceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VirtualAppliancesAPIService ListVirtualAppliances", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VirtualAppliancesAPI.ListVirtualAppliances(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VirtualAppliancesAPIService UpdateVirtualAppliance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var virtualApplianceId int64

		resp, httpRes, err := apiClient.VirtualAppliancesAPI.UpdateVirtualAppliance(context.Background(), virtualApplianceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
