/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
)

// checks if the SecurityGroupTagIdentityGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityGroupTagIdentityGetResponse{}

// SecurityGroupTagIdentityGetResponse The properties of the security group tag.
type SecurityGroupTagIdentityGetResponse struct {
	// The unique identifier specified in the UUID4 format. The key is used for all identity endpoints or security group tags.
	Key string `json:"key"`
	// The descriptive name assigned to the identity endpoint or security group tag.
	Label string `json:"label"`
	Status Status `json:"status"`
	// The unique identifier of the security group tag.
	TagId int64 `json:"tagId"`
	// The date and time in nanoseconds since the Unix Epoch when the system created the identity.
	CreatedAt int64 `json:"createdAt"`
	// The date and time in nanoseconds since the Unix Epoch when the system updated the identity.
	ModifiedAt int64 `json:"modifiedAt"`
	AdditionalProperties map[string]interface{}
}

type _SecurityGroupTagIdentityGetResponse SecurityGroupTagIdentityGetResponse

// NewSecurityGroupTagIdentityGetResponse instantiates a new SecurityGroupTagIdentityGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityGroupTagIdentityGetResponse(key string, label string, status Status, tagId int64, createdAt int64, modifiedAt int64) *SecurityGroupTagIdentityGetResponse {
	this := SecurityGroupTagIdentityGetResponse{}
	this.Key = key
	this.Label = label
	this.Status = status
	this.TagId = tagId
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	return &this
}

// NewSecurityGroupTagIdentityGetResponseWithDefaults instantiates a new SecurityGroupTagIdentityGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityGroupTagIdentityGetResponseWithDefaults() *SecurityGroupTagIdentityGetResponse {
	this := SecurityGroupTagIdentityGetResponse{}
	return &this
}

// GetKey returns the Key field value
func (o *SecurityGroupTagIdentityGetResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *SecurityGroupTagIdentityGetResponse) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetLabel(v string) {
	o.Label = v
}

// GetStatus returns the Status field value
func (o *SecurityGroupTagIdentityGetResponse) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetStatus(v Status) {
	o.Status = v
}

// GetTagId returns the TagId field value
func (o *SecurityGroupTagIdentityGetResponse) GetTagId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TagId
}

// GetTagIdOk returns a tuple with the TagId field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetTagIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagId, true
}

// SetTagId sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetTagId(v int64) {
	o.TagId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SecurityGroupTagIdentityGetResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *SecurityGroupTagIdentityGetResponse) GetModifiedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *SecurityGroupTagIdentityGetResponse) GetModifiedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *SecurityGroupTagIdentityGetResponse) SetModifiedAt(v int64) {
	o.ModifiedAt = v
}

func (o SecurityGroupTagIdentityGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityGroupTagIdentityGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["status"] = o.Status
	toSerialize["tagId"] = o.TagId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["modifiedAt"] = o.ModifiedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecurityGroupTagIdentityGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
		"status",
		"tagId",
		"createdAt",
		"modifiedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecurityGroupTagIdentityGetResponse := _SecurityGroupTagIdentityGetResponse{}

	err = json.Unmarshal(data, &varSecurityGroupTagIdentityGetResponse)

	if err != nil {
		return err
	}

	*o = SecurityGroupTagIdentityGetResponse(varSecurityGroupTagIdentityGetResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tagId")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecurityGroupTagIdentityGetResponse struct {
	value *SecurityGroupTagIdentityGetResponse
	isSet bool
}

func (v NullableSecurityGroupTagIdentityGetResponse) Get() *SecurityGroupTagIdentityGetResponse {
	return v.value
}

func (v *NullableSecurityGroupTagIdentityGetResponse) Set(val *SecurityGroupTagIdentityGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityGroupTagIdentityGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityGroupTagIdentityGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityGroupTagIdentityGetResponse(val *SecurityGroupTagIdentityGetResponse) *NullableSecurityGroupTagIdentityGetResponse {
	return &NullableSecurityGroupTagIdentityGetResponse{value: val, isSet: true}
}

func (v NullableSecurityGroupTagIdentityGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityGroupTagIdentityGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


