/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateSecurityGroupTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSecurityGroupTags{}

// UpdateSecurityGroupTags Update the properties of the security group tag.
type UpdateSecurityGroupTags struct {
	// The unique identifier specified in the UUID4 format. The key is used for all identity endpoints or security group tags.
	Key string `json:"key"`
	// The descriptive name assigned to the identity endpoint or security group tag.
	Label string `json:"label"`
	Status Status `json:"status"`
	// The unique identifier of the security group tag.
	TagId int64 `json:"tagId"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSecurityGroupTags UpdateSecurityGroupTags

// NewUpdateSecurityGroupTags instantiates a new UpdateSecurityGroupTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSecurityGroupTags(key string, label string, status Status, tagId int64) *UpdateSecurityGroupTags {
	this := UpdateSecurityGroupTags{}
	this.Key = key
	this.Label = label
	this.Status = status
	this.TagId = tagId
	return &this
}

// NewUpdateSecurityGroupTagsWithDefaults instantiates a new UpdateSecurityGroupTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSecurityGroupTagsWithDefaults() *UpdateSecurityGroupTags {
	this := UpdateSecurityGroupTags{}
	return &this
}

// GetKey returns the Key field value
func (o *UpdateSecurityGroupTags) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UpdateSecurityGroupTags) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UpdateSecurityGroupTags) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *UpdateSecurityGroupTags) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *UpdateSecurityGroupTags) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *UpdateSecurityGroupTags) SetLabel(v string) {
	o.Label = v
}

// GetStatus returns the Status field value
func (o *UpdateSecurityGroupTags) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateSecurityGroupTags) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateSecurityGroupTags) SetStatus(v Status) {
	o.Status = v
}

// GetTagId returns the TagId field value
func (o *UpdateSecurityGroupTags) GetTagId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TagId
}

// GetTagIdOk returns a tuple with the TagId field value
// and a boolean to check if the value has been set.
func (o *UpdateSecurityGroupTags) GetTagIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagId, true
}

// SetTagId sets field value
func (o *UpdateSecurityGroupTags) SetTagId(v int64) {
	o.TagId = v
}

func (o UpdateSecurityGroupTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSecurityGroupTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["status"] = o.Status
	toSerialize["tagId"] = o.TagId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSecurityGroupTags) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
		"status",
		"tagId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSecurityGroupTags := _UpdateSecurityGroupTags{}

	err = json.Unmarshal(data, &varUpdateSecurityGroupTags)

	if err != nil {
		return err
	}

	*o = UpdateSecurityGroupTags(varUpdateSecurityGroupTags)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tagId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSecurityGroupTags struct {
	value *UpdateSecurityGroupTags
	isSet bool
}

func (v NullableUpdateSecurityGroupTags) Get() *UpdateSecurityGroupTags {
	return v.value
}

func (v *NullableUpdateSecurityGroupTags) Set(val *UpdateSecurityGroupTags) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSecurityGroupTags) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSecurityGroupTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSecurityGroupTags(val *UpdateSecurityGroupTags) *NullableUpdateSecurityGroupTags {
	return &NullableUpdateSecurityGroupTags{value: val, isSet: true}
}

func (v NullableUpdateSecurityGroupTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSecurityGroupTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


