/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UpdateIdentitiesRequestInner - Provide an identity device for the list of identity devices. Provide a security group tag for the list of security group tags.
type UpdateIdentitiesRequestInner struct {
	UpdateIdentityDevices *UpdateIdentityDevices
	UpdateSecurityGroupTags *UpdateSecurityGroupTags
}

// UpdateIdentityDevicesAsUpdateIdentitiesRequestInner is a convenience function that returns UpdateIdentityDevices wrapped in UpdateIdentitiesRequestInner
func UpdateIdentityDevicesAsUpdateIdentitiesRequestInner(v *UpdateIdentityDevices) UpdateIdentitiesRequestInner {
	return UpdateIdentitiesRequestInner{
		UpdateIdentityDevices: v,
	}
}

// UpdateSecurityGroupTagsAsUpdateIdentitiesRequestInner is a convenience function that returns UpdateSecurityGroupTags wrapped in UpdateIdentitiesRequestInner
func UpdateSecurityGroupTagsAsUpdateIdentitiesRequestInner(v *UpdateSecurityGroupTags) UpdateIdentitiesRequestInner {
	return UpdateIdentitiesRequestInner{
		UpdateSecurityGroupTags: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UpdateIdentitiesRequestInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UpdateIdentityDevices
	err = newStrictDecoder(data).Decode(&dst.UpdateIdentityDevices)
	if err == nil {
		jsonUpdateIdentityDevices, _ := json.Marshal(dst.UpdateIdentityDevices)
		if string(jsonUpdateIdentityDevices) == "{}" { // empty struct
			dst.UpdateIdentityDevices = nil
		} else {
			if err = validator.Validate(dst.UpdateIdentityDevices); err != nil {
				dst.UpdateIdentityDevices = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateIdentityDevices = nil
	}

	// try to unmarshal data into UpdateSecurityGroupTags
	err = newStrictDecoder(data).Decode(&dst.UpdateSecurityGroupTags)
	if err == nil {
		jsonUpdateSecurityGroupTags, _ := json.Marshal(dst.UpdateSecurityGroupTags)
		if string(jsonUpdateSecurityGroupTags) == "{}" { // empty struct
			dst.UpdateSecurityGroupTags = nil
		} else {
			if err = validator.Validate(dst.UpdateSecurityGroupTags); err != nil {
				dst.UpdateSecurityGroupTags = nil
			} else {
				match++
			}
		}
	} else {
		dst.UpdateSecurityGroupTags = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UpdateIdentityDevices = nil
		dst.UpdateSecurityGroupTags = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UpdateIdentitiesRequestInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UpdateIdentitiesRequestInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateIdentitiesRequestInner) MarshalJSON() ([]byte, error) {
	if src.UpdateIdentityDevices != nil {
		return json.Marshal(&src.UpdateIdentityDevices)
	}

	if src.UpdateSecurityGroupTags != nil {
		return json.Marshal(&src.UpdateSecurityGroupTags)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UpdateIdentitiesRequestInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UpdateIdentityDevices != nil {
		return obj.UpdateIdentityDevices
	}

	if obj.UpdateSecurityGroupTags != nil {
		return obj.UpdateSecurityGroupTags
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UpdateIdentitiesRequestInner) GetActualInstanceValue() (interface{}) {
	if obj.UpdateIdentityDevices != nil {
		return *obj.UpdateIdentityDevices
	}

	if obj.UpdateSecurityGroupTags != nil {
		return *obj.UpdateSecurityGroupTags
	}

	// all schemas are nil
	return nil
}

type NullableUpdateIdentitiesRequestInner struct {
	value *UpdateIdentitiesRequestInner
	isSet bool
}

func (v NullableUpdateIdentitiesRequestInner) Get() *UpdateIdentitiesRequestInner {
	return v.value
}

func (v *NullableUpdateIdentitiesRequestInner) Set(val *UpdateIdentitiesRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateIdentitiesRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateIdentitiesRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateIdentitiesRequestInner(val *UpdateIdentitiesRequestInner) *NullableUpdateIdentitiesRequestInner {
	return &NullableUpdateIdentitiesRequestInner{value: val, isSet: true}
}

func (v NullableUpdateIdentitiesRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateIdentitiesRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


