/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
)

// checks if the GetIdentities200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIdentities200Response{}

// GetIdentities200Response The metadata for the response and the list of identity endpoints or security group tags in the collection.
type GetIdentities200Response struct {
	// The total number of identities provisioned in the organization.
	Total int64 `json:"total"`
	// The number of items returned in the page. The default value of the `limit` is `100`.
	Limit int64 `json:"limit"`
	// The place in the collection where the system started to read the resources. The default value of the `offset` is `0`.
	Offset int64 `json:"offset"`
	// The list of identities in the collection returned for either the `device` or `securityGroupTag` identity type.
	Data []IdentitiesGetResponseInner `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _GetIdentities200Response GetIdentities200Response

// NewGetIdentities200Response instantiates a new GetIdentities200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIdentities200Response(total int64, limit int64, offset int64, data []IdentitiesGetResponseInner) *GetIdentities200Response {
	this := GetIdentities200Response{}
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	this.Data = data
	return &this
}

// NewGetIdentities200ResponseWithDefaults instantiates a new GetIdentities200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIdentities200ResponseWithDefaults() *GetIdentities200Response {
	this := GetIdentities200Response{}
	var limit int64 = 100
	this.Limit = limit
	var offset int64 = 0
	this.Offset = offset
	return &this
}

// GetTotal returns the Total field value
func (o *GetIdentities200Response) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetIdentities200Response) SetTotal(v int64) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *GetIdentities200Response) GetLimit() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *GetIdentities200Response) SetLimit(v int64) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *GetIdentities200Response) GetOffset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *GetIdentities200Response) SetOffset(v int64) {
	o.Offset = v
}

// GetData returns the Data field value
func (o *GetIdentities200Response) GetData() []IdentitiesGetResponseInner {
	if o == nil {
		var ret []IdentitiesGetResponseInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetIdentities200Response) GetDataOk() ([]IdentitiesGetResponseInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetIdentities200Response) SetData(v []IdentitiesGetResponseInner) {
	o.Data = v
}

func (o GetIdentities200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIdentities200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetIdentities200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"limit",
		"offset",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIdentities200Response := _GetIdentities200Response{}

	err = json.Unmarshal(data, &varGetIdentities200Response)

	if err != nil {
		return err
	}

	*o = GetIdentities200Response(varGetIdentities200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "total")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "offset")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetIdentities200Response struct {
	value *GetIdentities200Response
	isSet bool
}

func (v NullableGetIdentities200Response) Get() *GetIdentities200Response {
	return v.value
}

func (v *NullableGetIdentities200Response) Set(val *GetIdentities200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIdentities200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIdentities200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIdentities200Response(val *GetIdentities200Response) *NullableGetIdentities200Response {
	return &NullableGetIdentities200Response{value: val, isSet: true}
}

func (v NullableGetIdentities200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIdentities200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


