/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
)

// checks if the IdentityEndpointsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityEndpointsGetResponse{}

// IdentityEndpointsGetResponse The properties of the identity endpoint.
type IdentityEndpointsGetResponse struct {
	// The unique identifier specified in the UUID4 format. The key is used for all identity endpoints or security group tags.
	Key string `json:"key"`
	// The descriptive name assigned to the identity endpoint or security group tag.
	Label string `json:"label"`
	Status Status `json:"status"`
	// The attribute used to authenticate the identity endpoint.
	AuthName string `json:"authName"`
	// The date and time in nanoseconds since the Unix Epoch when the system created the identity.
	CreatedAt int64 `json:"createdAt"`
	// The date and time in nanoseconds since the Unix Epoch when the system updated the identity.
	ModifiedAt int64 `json:"modifiedAt"`
	AdditionalProperties map[string]interface{}
}

type _IdentityEndpointsGetResponse IdentityEndpointsGetResponse

// NewIdentityEndpointsGetResponse instantiates a new IdentityEndpointsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityEndpointsGetResponse(key string, label string, status Status, authName string, createdAt int64, modifiedAt int64) *IdentityEndpointsGetResponse {
	this := IdentityEndpointsGetResponse{}
	this.Key = key
	this.Label = label
	this.Status = status
	this.AuthName = authName
	this.CreatedAt = createdAt
	this.ModifiedAt = modifiedAt
	return &this
}

// NewIdentityEndpointsGetResponseWithDefaults instantiates a new IdentityEndpointsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityEndpointsGetResponseWithDefaults() *IdentityEndpointsGetResponse {
	this := IdentityEndpointsGetResponse{}
	return &this
}

// GetKey returns the Key field value
func (o *IdentityEndpointsGetResponse) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *IdentityEndpointsGetResponse) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *IdentityEndpointsGetResponse) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *IdentityEndpointsGetResponse) SetLabel(v string) {
	o.Label = v
}

// GetStatus returns the Status field value
func (o *IdentityEndpointsGetResponse) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IdentityEndpointsGetResponse) SetStatus(v Status) {
	o.Status = v
}

// GetAuthName returns the AuthName field value
func (o *IdentityEndpointsGetResponse) GetAuthName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthName
}

// GetAuthNameOk returns a tuple with the AuthName field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetAuthNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthName, true
}

// SetAuthName sets field value
func (o *IdentityEndpointsGetResponse) SetAuthName(v string) {
	o.AuthName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IdentityEndpointsGetResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IdentityEndpointsGetResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetModifiedAt returns the ModifiedAt field value
func (o *IdentityEndpointsGetResponse) GetModifiedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ModifiedAt
}

// GetModifiedAtOk returns a tuple with the ModifiedAt field value
// and a boolean to check if the value has been set.
func (o *IdentityEndpointsGetResponse) GetModifiedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModifiedAt, true
}

// SetModifiedAt sets field value
func (o *IdentityEndpointsGetResponse) SetModifiedAt(v int64) {
	o.ModifiedAt = v
}

func (o IdentityEndpointsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityEndpointsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["status"] = o.Status
	toSerialize["authName"] = o.AuthName
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["modifiedAt"] = o.ModifiedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdentityEndpointsGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
		"status",
		"authName",
		"createdAt",
		"modifiedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdentityEndpointsGetResponse := _IdentityEndpointsGetResponse{}

	err = json.Unmarshal(data, &varIdentityEndpointsGetResponse)

	if err != nil {
		return err
	}

	*o = IdentityEndpointsGetResponse(varIdentityEndpointsGetResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "status")
		delete(additionalProperties, "authName")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "modifiedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentityEndpointsGetResponse struct {
	value *IdentityEndpointsGetResponse
	isSet bool
}

func (v NullableIdentityEndpointsGetResponse) Get() *IdentityEndpointsGetResponse {
	return v.value
}

func (v *NullableIdentityEndpointsGetResponse) Set(val *IdentityEndpointsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityEndpointsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityEndpointsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityEndpointsGetResponse(val *IdentityEndpointsGetResponse) *NullableIdentityEndpointsGetResponse {
	return &NullableIdentityEndpointsGetResponse{value: val, isSet: true}
}

func (v NullableIdentityEndpointsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityEndpointsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


