/*
Cisco Secure Access Identities Registration API

Manage the Secure Access identity endpoints and security groups tags (SGTs) for the identities in the organization.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identities

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateIdentityDevices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateIdentityDevices{}

// UpdateIdentityDevices Update the properties of the identity device.
type UpdateIdentityDevices struct {
	// The unique identifier specified in the UUID4 format. The key is used for all identity endpoints or security group tags.
	Key string `json:"key"`
	// The descriptive name assigned to the identity endpoint or security group tag.
	Label string `json:"label"`
	Status Status `json:"status"`
	// The attribute used to authenticate the identity endpoint.
	AuthName string `json:"authName"`
	// The globally unique identifier for the Active Directory integration.
	GuidHash *string `json:"guidHash,omitempty"`
	// The configured domain name for the identity device.
	DomainName *string `json:"domainName,omitempty"`
	// The configured SAM account name for the identity device.
	SamAccountName *string `json:"samAccountName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateIdentityDevices UpdateIdentityDevices

// NewUpdateIdentityDevices instantiates a new UpdateIdentityDevices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateIdentityDevices(key string, label string, status Status, authName string) *UpdateIdentityDevices {
	this := UpdateIdentityDevices{}
	this.Key = key
	this.Label = label
	this.Status = status
	this.AuthName = authName
	return &this
}

// NewUpdateIdentityDevicesWithDefaults instantiates a new UpdateIdentityDevices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateIdentityDevicesWithDefaults() *UpdateIdentityDevices {
	this := UpdateIdentityDevices{}
	return &this
}

// GetKey returns the Key field value
func (o *UpdateIdentityDevices) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UpdateIdentityDevices) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *UpdateIdentityDevices) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *UpdateIdentityDevices) SetLabel(v string) {
	o.Label = v
}

// GetStatus returns the Status field value
func (o *UpdateIdentityDevices) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateIdentityDevices) SetStatus(v Status) {
	o.Status = v
}

// GetAuthName returns the AuthName field value
func (o *UpdateIdentityDevices) GetAuthName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthName
}

// GetAuthNameOk returns a tuple with the AuthName field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetAuthNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthName, true
}

// SetAuthName sets field value
func (o *UpdateIdentityDevices) SetAuthName(v string) {
	o.AuthName = v
}

// GetGuidHash returns the GuidHash field value if set, zero value otherwise.
func (o *UpdateIdentityDevices) GetGuidHash() string {
	if o == nil || IsNil(o.GuidHash) {
		var ret string
		return ret
	}
	return *o.GuidHash
}

// GetGuidHashOk returns a tuple with the GuidHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetGuidHashOk() (*string, bool) {
	if o == nil || IsNil(o.GuidHash) {
		return nil, false
	}
	return o.GuidHash, true
}

// HasGuidHash returns a boolean if a field has been set.
func (o *UpdateIdentityDevices) HasGuidHash() bool {
	if o != nil && !IsNil(o.GuidHash) {
		return true
	}

	return false
}

// SetGuidHash gets a reference to the given string and assigns it to the GuidHash field.
func (o *UpdateIdentityDevices) SetGuidHash(v string) {
	o.GuidHash = &v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *UpdateIdentityDevices) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *UpdateIdentityDevices) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *UpdateIdentityDevices) SetDomainName(v string) {
	o.DomainName = &v
}

// GetSamAccountName returns the SamAccountName field value if set, zero value otherwise.
func (o *UpdateIdentityDevices) GetSamAccountName() string {
	if o == nil || IsNil(o.SamAccountName) {
		var ret string
		return ret
	}
	return *o.SamAccountName
}

// GetSamAccountNameOk returns a tuple with the SamAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateIdentityDevices) GetSamAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.SamAccountName) {
		return nil, false
	}
	return o.SamAccountName, true
}

// HasSamAccountName returns a boolean if a field has been set.
func (o *UpdateIdentityDevices) HasSamAccountName() bool {
	if o != nil && !IsNil(o.SamAccountName) {
		return true
	}

	return false
}

// SetSamAccountName gets a reference to the given string and assigns it to the SamAccountName field.
func (o *UpdateIdentityDevices) SetSamAccountName(v string) {
	o.SamAccountName = &v
}

func (o UpdateIdentityDevices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateIdentityDevices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["status"] = o.Status
	toSerialize["authName"] = o.AuthName
	if !IsNil(o.GuidHash) {
		toSerialize["guidHash"] = o.GuidHash
	}
	if !IsNil(o.DomainName) {
		toSerialize["domainName"] = o.DomainName
	}
	if !IsNil(o.SamAccountName) {
		toSerialize["samAccountName"] = o.SamAccountName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateIdentityDevices) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
		"status",
		"authName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateIdentityDevices := _UpdateIdentityDevices{}

	err = json.Unmarshal(data, &varUpdateIdentityDevices)

	if err != nil {
		return err
	}

	*o = UpdateIdentityDevices(varUpdateIdentityDevices)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "label")
		delete(additionalProperties, "status")
		delete(additionalProperties, "authName")
		delete(additionalProperties, "guidHash")
		delete(additionalProperties, "domainName")
		delete(additionalProperties, "samAccountName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateIdentityDevices struct {
	value *UpdateIdentityDevices
	isSet bool
}

func (v NullableUpdateIdentityDevices) Get() *UpdateIdentityDevices {
	return v.value
}

func (v *NullableUpdateIdentityDevices) Set(val *UpdateIdentityDevices) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateIdentityDevices) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateIdentityDevices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateIdentityDevices(val *UpdateIdentityDevices) *NullableUpdateIdentityDevices {
	return &NullableUpdateIdentityDevices{value: val, isSet: true}
}

func (v NullableUpdateIdentityDevices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateIdentityDevices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


