/*
Cisco Secure Access Content Categories API

Testing ContentCategoriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package contentcategories

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CiscoDevNet/go-ciscosecureaccess/contentcategories"
)

func Test_contentcategories_ContentCategoriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentCategoriesAPIService GetCategorySettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContentCategoriesAPI.GetCategorySettings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
