/*
Cisco Secure Access Alerting API

Testing AlertRulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package alerting

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CiscoDevNet/go-ciscosecureaccess/alerting"
)

func Test_alerting_AlertRulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AlertRulesAPIService CreateAlertRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertRulesAPI.CreateAlertRule(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertRulesAPIService DeleteAlertRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertRulesAPI.DeleteAlertRules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertRulesAPIService GetAlertRuleById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId int64

		resp, httpRes, err := apiClient.AlertRulesAPI.GetAlertRuleById(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertRulesAPIService ListAlertRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertRulesAPI.ListAlertRules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertRulesAPIService UpdateAlertRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId int64

		resp, httpRes, err := apiClient.AlertRulesAPI.UpdateAlertRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlertRulesAPIService UpdateAlertRulesStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlertRulesAPI.UpdateAlertRulesStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
